const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve('dist'),context={window:{},document:{querySelector(){}}};vm.createContext(context);
for(const file of ['data','history-data','universe-data','component-data','core'])vm.runInContext(fs.readFileSync(path.join(root,file+'.js'),'utf8'),context);
vm.runInContext('globalThis.records=catalog;globalThis.unitMap=units;globalThis.groups=categories;',context);
const records=context.records,images=fs.existsSync('dist/images.json')?JSON.parse(fs.readFileSync('dist/images.json','utf8')):{};
const SITE='https://www.pcpartperformance.com',pageUrls=new Set();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mark='<svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M9 29V12a4 4 0 0 1 4-4h8a7 7 0 0 1 0 14h-5" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="M20 32V19a4 4 0 0 1 4-4h3a6 6 0 0 1 0 12h-2" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const arrow='<span aria-hidden="true">↗</span>';
const categoryPaths={gpu:'graphics-cards',cpu:'processors',ram:'memory',ssd:'solid-state-drives'};
const categoryNames={gpu:'Graphics cards',cpu:'Processors',ram:'Memory',ssd:'SSDs'};
function creditLine(a){return a.attribution?`<p class="image-credit">Photo: ${esc(a.attribution.replace(/<[^>]*>/g,''))}${a.license?` · <a href="${esc(a.licenseUrl||a.sourceUrl)}" target="_blank" rel="noopener">${esc(a.license)}</a>`:''}</p>`:'';}
const groupName=id=>context.groups.find(g=>g[0]===id)?.[1]||id;
const safeJson=value=>JSON.stringify(value).replace(/</g,'\\u003c');
const adSlot=(type='responsive',className='')=>`<div class="ad-slot ${className}" data-ad-slot="${type}" aria-label="Advertisement"></div>`;

function shell(title,route,body,options={}){
 const active=route==='record'||route==='guide'?'learn':route;
 const interactive=['compare','hardware','builder'].includes(route);
 const pathName=options.canonicalPath??(route==='home'?'/':`/${route}/`),canonical=SITE+pathName;
 const description=options.description||title+'. Compare specifications, explore product photos, and find compatible PC parts.';
 const indexable=options.indexable!==false;
 const schema=options.schema||{'@context':'https://schema.org','@type':'WebPage',name:title,description,url:canonical,isPartOf:{'@type':'WebSite',name:'PC Part Performance',url:SITE+'/'}};
 return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)} · PC Part Performance</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><meta name="robots" content="${indexable?'index,follow,max-image-preview:large':'noindex,follow'}">
<meta property="og:type" content="${route==='guide'||route==='article'?'article':'website'}"><meta property="og:site_name" content="PC Part Performance"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><script type="application/ld+json">${safeJson(schema)}</script>
<meta name="theme-color" content="#101310"><meta name="color-scheme" content="dark light"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><script src="/theme.js"></script>
${route==='builder'?'<link rel="stylesheet" href="/builder-legacy.css">':''}<link rel="stylesheet" href="/design.css"><link rel="stylesheet" href="/refinement.css"><link rel="stylesheet" href="/motion.css"><link rel="stylesheet" href="/ads.css">
<script src="/site-ui.js" defer></script>${interactive?'\n'+['data','history-data','universe-data','component-data','core','image-catalog','interface'].map(f=>`<script src="/${f}.js" defer></script>`).join('\n'):''}
${route==='builder'?'<script src="/builder-v2.js" defer></script>':''}<script src="/motion.js" defer></script><script src="/ads.js" defer></script>
</head><body data-page="${route}"${options.category?` data-category="${options.category}"`:''}>
<a class="skip" href="#main">Skip to content</a>
<header class="site-header"><a class="brand" href="/" aria-label="PC Part Performance home"><span class="brand-mark">${mark}</span><span>PC Part<span class="brand-sub">Performance</span></span></a><nav class="liquid-nav" aria-label="Main navigation"><span class="nav-indicator" aria-hidden="true"></span>${[['compare','Compare'],['hardware','Hardware'],['builder','PC builder'],['learn','Learn']].map(([id,label])=>`<a href="/${id}/"${active===id?' aria-current="page"':''}>${label}</a>`).join('')}</nav><button class="theme-toggle" aria-label="Switch color theme"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M20.6 13.2A9 9 0 0 1 10.8 3.4a9 9 0 1 0 9.8 9.8Z"/></svg><span class="theme-label">Theme</span></button></header>
<main id="main" tabindex="-1">${body}</main>
<footer class="site-footer"><a class="footer-brand" href="/"><span class="footer-logo">${mark}</span><span>PC Part Performance</span></a><div><a href="/compare/">Compare</a><a href="/hardware/">Hardware</a><a href="/builder/">PC builder</a><a href="/learn/">Learn</a><a href="/methodology/">Data & photos</a><a href="/privacy/">Privacy</a><button class="manage-ads" type="button">Ad choices</button></div></footer>
<div id="toast" role="status" aria-live="polite"></div><dialog id="part-picker" aria-labelledby="picker-title"><div class="dialog-top"><div><h2 id="picker-title">Choose a part</h2><p id="picker-category-label"></p></div><button class="icon-button" id="close-picker" aria-label="Close hardware picker">×</button></div><label class="sr-only" for="picker-query">Search hardware</label><input type="search" id="picker-query" placeholder="Search model or brand…"><div id="picker-results"></div></dialog>
</body></html>`;
}
function write(route,html){const dir=path.join(root,route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);pageUrls.add('/'+(route?route.replace(/^\/+|\/+$/g,'')+'/':''));}
function heading(title,description,action=''){return `<div class="page-heading"><div><h1>${title}</h1>${description?`<p>${description}</p>`:''}</div>${action}</div>`;}
function picture(p,cls='',eager=false){const a=images[p.id],label=a?.official&&a.kind==='exact'?'Official product photo':a?.kind==='reference'?'Reference photo':a?.kind==='family'?'Product family photo':'Product photo';return a?`<figure class="hardware-photo ${cls}"><img src="${esc(a.src)}" alt="${esc(a.picturedModel)}${a.kind==='reference'?' — reference photo, not this exact model':a.kind==='family'?' — product family photo':''}" loading="${eager?'eager':'lazy'}" decoding="async" width="800" height="500"><figcaption>${label} · ${esc(a.picturedModel)}</figcaption></figure>`:`<div class="photo-unavailable"><span>${esc(p.brand)}</span><strong>${esc(p.architecture)}</strong><small>Photo not indexed</small></div>`;}

write('',shell('Compare PC parts','home',`
<section class="home-hero"><div class="hero-copy"><span class="hero-kicker">PC PART PERFORMANCE</span><h1>Compare parts.<br>Find your <span>upgrade.</span></h1><p>A clear, side-by-side look at the hardware<br class="desktop-break"> that goes into your next PC.</p><a class="button primary magnetic" href="/compare/">Start comparing ${arrow}</a><a class="subtle-link" href="/builder/">Or build a complete PC <span aria-hidden="true">→</span></a></div>
<a class="hero-matchup" href="/compare/?parts=rtx5070,rtx5060ti16" aria-label="Compare RTX 5070 with RTX 5060 Ti"><div class="matchup-top"><span>GRAPHICS CARDS</span><span>Explore this comparison ${arrow}</span></div><div class="hero-product first"><div class="hero-product-label"><small>NVIDIA GEFORCE</small><strong>RTX 5070</strong><span>12 GB GDDR7</span></div><div class="hero-image-stage"><img src="/assets/rtx-5070.png" alt="ASUS Prime GeForce RTX 5070" width="1725" height="493" fetchpriority="high"></div></div><div class="matchup-divider"><span class="versus">VS</span></div><div class="hero-product second"><div class="hero-product-label"><small>NVIDIA GEFORCE</small><strong>RTX 5060 Ti</strong><span>16 GB GDDR7</span></div><div class="hero-image-stage"><img src="/assets/rtx-5060-ti.png" alt="ASUS Dual GeForce RTX 5060 Ti 16 GB" width="1725" height="430"></div></div><div class="matchup-bottom"><span>Specs, photos, and differences.</span><span class="round-arrow" aria-hidden="true">↗</span></div></a></section>
<section class="home-browse" aria-labelledby="browse-title"><div class="section-heading"><h2 id="browse-title">What are you upgrading?</h2><a class="subtle-link" href="/hardware/">All hardware →</a></div><div class="category-links">${Object.entries(categoryPaths).map(([cat,slug],i)=>`<a href="/hardware/${slug}/"><span class="category-index">0${i+1}</span><strong>${categoryNames[cat]}</strong>${arrow}</a>`).join('')}</div></section>${adSlot('responsive')}
<section class="home-guidance" aria-labelledby="upgrade-title"><div class="section-heading"><div><h2 id="upgrade-title">Start with what slows you down.</h2><p>Choose an upgrade around the work you actually do.</p></div></div><div class="upgrade-grid"><article><h3>Games feel slow</h3><p>Compare graphics cards for your resolution. Check independent game tests, then look at video memory, power, and case clearance.</p><a class="subtle-link" href="/learn/gpu/">Understand GPU specs <span aria-hidden="true">→</span></a></article><article><h3>Work takes too long</h3><p>For rendering, compiling, or editing, compare CPUs using tests of your applications. Confirm motherboard and BIOS support.</p><a class="subtle-link" href="/learn/cpu/">Understand CPU specs <span aria-hidden="true">→</span></a></article><article><h3>You’re running out of room</h3><p>RAM gives active apps more working space. An SSD stores your files and games. Check which one you need before buying.</p><div class="guidance-links"><a class="subtle-link" href="/learn/ram/">RAM guide <span aria-hidden="true">→</span></a><a class="subtle-link" href="/learn/ssd/">SSD guide <span aria-hidden="true">→</span></a></div></article></div></section>
<section class="home-fit" aria-labelledby="fit-title"><div class="fit-intro"><h2 id="fit-title">A good upgrade<br>needs to fit.</h2><p>Check your whole system before choosing a part.</p><a class="button primary magnetic" href="/builder/">Check your build ${arrow}</a></div><ol class="fit-checklist"><li><h3>Match the platform</h3><p>Check the CPU socket, motherboard support, and RAM generation.</p></li><li><h3>Leave room and power</h3><p>Confirm card length, cooler clearance, and the power supply’s connectors.</p></li><li><h3>Check the exact model</h3><p>Capacities and partner designs can differ. Follow the source links and verify the version you plan to buy.</p></li></ol></section>${adSlot('native')}`,{canonicalPath:'/',description:'Compare PC hardware specifications, explore compatible upgrades, and build a PC using a sourced catalog of processors, graphics cards, memory, storage, and more.'}));

write('compare',shell('Compare hardware','compare',`
${heading('Compare hardware.','Pick up to four parts. See the differences side by side.','<button class="button secondary" id="export-csv">Export CSV <span aria-hidden="true">↓</span></button>')}
<div class="compare-controls"><div class="segmented" id="compare-categories" aria-label="Popular hardware categories"></div><div class="more-category"><details class="category-menu" id="more-category-menu"><summary aria-label="Choose another hardware category"><span class="category-menu-icon" id="category-menu-icon" aria-hidden="true"></span><span class="category-menu-copy"><small>More hardware</small><strong id="category-menu-label">Choose a category</strong></span><span class="category-menu-chevron" aria-hidden="true">⌄</span></summary><div class="category-menu-panel"><div class="category-menu-heading"><strong>All categories</strong><span>Choose what you want to compare</span></div><div class="category-menu-options" id="category-menu-options"></div></div></details><label class="sr-only" for="more-category">More hardware categories</label><select class="sr-only" id="more-category" tabindex="-1" aria-hidden="true"><option value="">More categories</option></select></div></div>
<section aria-label="Selected hardware" id="comparison-cards" class="comparison-cards"></section><div class="compare-options"><button class="text-button" id="add-comparison">＋ Add a part</button><label class="switch-label"><input type="checkbox" id="differences-only"><span class="switch-track" aria-hidden="true"></span>Only differences</label></div>
<section class="comparison-data" aria-labelledby="overview-title"><div class="section-heading"><h2 id="overview-title">Key specifications</h2><span class="source-caption">Reference specifications</span></div><div class="metric-grid" id="metric-grid"></div><p class="data-note">These are hardware specifications, not game FPS.</p></section><section class="specifications"><div class="section-heading"><h2>Full comparison</h2><span class="muted" id="spec-count"></span></div><div class="table-scroll" id="comparison-table"></div><div id="comparison-warning"></div><details class="source-details"><summary>Sources, photos & model notes</summary><div id="comparison-sources"></div></details></section>${adSlot('responsive')}`,{canonicalPath:'/compare/',indexable:false,description:'Compare up to four PC parts side by side using sourced reference specifications and model notes.'}));

function library(category=''){const seed=records.filter(p=>!category||p.cat===category).slice(0,24);return `${heading(category?categoryNames[category]+'.':'Explore hardware.','Find a model, open its specifications, or add it to your comparison.')}<div class="catalog-tools"><label class="search-field"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="catalog-search" type="search" placeholder="Search model or brand…" aria-label="Search hardware"></label><select id="catalog-category" aria-label="Hardware category"></select><select id="catalog-era" aria-label="Release period"><option value="all">All generations</option><option value="modern">2020–present</option><option value="legacy">Before 2020</option></select><select id="catalog-sort" aria-label="Sort hardware"><option value="new">Newest first</option><option value="old">Oldest first</option><option value="name">Name A–Z</option></select></div><div class="catalog-meta"><span id="catalog-summary" aria-live="polite">${seed.length} featured records; use filters to explore the full catalog.</span><a class="selection-link" href="/compare/" id="selected-link">Open comparison →</a></div><div class="table-scroll"><table class="hardware-table"><thead><tr><th>Hardware</th><th>Category</th><th>Released</th><th>Specification</th><th><span class="sr-only">Compare</span></th></tr></thead><tbody id="hardware-rows">${seed.map(p=>`<tr><td><a href="/learn/${encodeURIComponent(p.id)}.html"><strong>${esc(p.name)}</strong><span>${esc(p.brand)}</span></a></td><td>${esc(groupName(p.cat))}</td><td>${esc(p.year||'—')}</td><td>${esc(p.summary)}</td><td><a href="/compare/?parts=${encodeURIComponent(p.id)}">Compare</a></td></tr>`).join('')}</tbody></table></div><div class="empty-message" id="catalog-empty" hidden>No matching hardware. Try a different model or category.</div><button class="button secondary load-more" id="catalog-more">Show more</button>${adSlot('responsive')}`;}
write('hardware',shell('Hardware catalog','hardware',library(),{canonicalPath:'/hardware/',description:'Browse a sourced catalog of PC hardware and devices, then open specifications or add parts to a side-by-side comparison.'}));
for(const [cat,slug] of Object.entries(categoryPaths))write('hardware/'+slug,shell(categoryNames[cat],'hardware',library(cat),{category:cat,canonicalPath:`/hardware/${slug}/`,description:`Browse ${categoryNames[cat].toLowerCase()} with sourced specifications, model notes, photos, and comparison links.`}));

const guides=[
{cat:'gpu',title:'Graphics cards',subtitle:'Understand the part that renders your games.',terms:[['Video memory (VRAM)','Stores textures and graphics data. More capacity can help at high resolutions, but capacity alone is not speed.'],['Memory bandwidth','How quickly the GPU accesses memory, measured in GB/s. Compare game tests as well as this specification.'],['Board power','A reference power rating in watts. Check the exact card’s connectors, cooling, and physical size.']]},
{cat:'cpu',title:'Processors',subtitle:'Understand the chip at the center of your PC.',terms:[['Cores and threads','Cores handle processing work. Extra threads can help supported workloads; more cores do not always mean faster games.'],['Clock speed','How frequently a processor operates. GHz comparisons are most useful within the same architecture.'],['Socket and platform','The CPU must match the motherboard socket, chipset support, and BIOS. Use the builder to check indexed compatibility.']]},
{cat:'ram',title:'Memory',subtitle:'Choose the right RAM for your platform.',terms:[['Capacity','Working memory available to the system, measured in GB. Add the capacity of all installed modules.'],['DDR generation','DDR3, DDR4, and DDR5 require compatible hardware. Desktop DIMMs and laptop SODIMMs also differ.'],['Speed and latency','Transfer rate describes data movement. CAS latency is measured in clock cycles; consider both rather than treating either as a score.']]},
{cat:'ssd',title:'SSDs',subtitle:'Choose storage that fits your board and workload.',terms:[['Capacity','How much data the drive can store. Check that specifications describe the exact capacity you intend to buy.'],['Interface and shape','SATA and NVMe describe interfaces; M.2 is a form factor. Match interface, length, and connector to your system.'],['Read speed and endurance','Sequential speed is an advertised maximum, not a game-loading result. Endurance describes the rated write workload, usually in TBW.']]}
];
const articles=[
  {slug:'cpu-socket-chipset-bios-compatibility',title:'CPU socket, chipset, and BIOS compatibility',description:'Why a matching CPU socket does not guarantee motherboard support.',sections:[['The socket is only the physical interface','A processor must fit the motherboard socket, but the board also needs electrical support, a compatible chipset policy, and firmware that recognizes that exact CPU. Two products carrying the same socket name can still be incompatible.'],['Check the support list','Find the motherboard manufacturer’s CPU support page, match the exact board model and hardware revision, then note the minimum BIOS version. Ask whether the board can update firmware without a supported CPU installed.'],['Before buying','Confirm socket, support list, BIOS version, cooler mounting, memory generation, power delivery, and operating-system requirements. The builder can screen indexed fields, but the manufacturer list is the final reference.']]},
  {slug:'cpu-cores-threads-clocks-ipc-cache',title:'CPU cores, threads, clocks, IPC, and cache',description:'How to compare processor specifications without turning one number into a universal score.',sections:[['Different numbers answer different questions','Core count describes parallel resources; threads describe schedulable work; clock speed describes cycles per second. IPC is workload-dependent, and cache can reduce slower memory access.'],['Compare within context','Clock comparisons are most useful within the same architecture. More cores help software that can use them, while lightly threaded tasks depend more on per-core behavior and latency.'],['Use workload evidence','Start with measurements of the application, compiler, renderer, or game you use. Check test configuration, power limits, memory, cooling, and software version before treating two results as comparable.']]},
  {slug:'gpu-vram-bandwidth-bus-width',title:'GPU VRAM, bandwidth, and bus width',description:'What graphics memory capacity and throughput can—and cannot—tell you.',sections:[['Capacity prevents a specific bottleneck','VRAM holds textures, frame buffers, geometry, and working data. Too little can cause stutter or reduced settings, but unused extra capacity does not automatically increase rendering speed.'],['Bandwidth is a system','Bus width, memory data rate, compression, and cache design together affect effective throughput. A narrower bus on a newer architecture is not automatically slower.'],['Choose for the workload','Use measurements at your target resolution and settings. Check the exact card’s capacity, memory type, power, cooler, connectors, and case clearance.']]},
  {slug:'gpu-power-connectors-psu-clearance',title:'GPU power, connectors, PSU capacity, and clearance',description:'A practical fit check before installing a graphics card.',sections:[['Power is more than a wattage label','Compare the exact board power and manufacturer PSU recommendation. Account for CPU and other components, connector type, cable guidance, and transient behavior.'],['Physical fit has several dimensions','Verify card length, height, thickness or slot count, power-plug clearance, radiator position, and airflow. Partner cards using the same GPU can differ substantially.'],['Installation checklist','Use dedicated cables as the PSU maker directs, seat connectors fully, support heavy cards, and confirm that no cable is sharply bent at the plug. Follow the exact product manuals.']]},
  {slug:'why-specs-cannot-predict-fps',title:'Why specifications cannot predict exact game FPS',description:'Why cores, clocks, bandwidth, and synthetic scores do not equal a guaranteed frame rate.',sections:[['Games stress systems differently','Engines vary in CPU scheduling, shaders, memory behavior, ray tracing, asset streaming, and driver optimization. The same GPU can produce very different results across games and settings.'],['The rest of the test system matters','Processor, RAM, cooling, power limits, driver, game patch, background tasks, resolution, upscaling, and scene selection all influence results.'],['Use reproducible tests','Prefer recent tests that disclose hardware, software, settings, run method, averages, and frame-time behavior. Specifications help explain a result; they are not a substitute for it.']]},
  {slug:'ram-speed-cas-first-word-latency',title:'RAM MT/s, CAS latency, and first-word latency',description:'How transfer rate and timing relate, with a simple latency estimate.',sections:[['MT/s is a transfer rate','DDR memory performs transfers on both clock edges, so the advertised data rate is not the physical clock frequency. Higher MT/s increases peak bandwidth when the platform supports it.'],['CAS is measured in cycles','A rough CAS latency estimate in nanoseconds is 2000 × CL ÷ MT/s. This compares one timing only and does not represent every memory delay or application outcome.'],['Platform settings matter','The CPU memory controller, motherboard, module layout, profile support, voltage, and firmware affect stable operation. Confirm supported configurations before buying a high-speed kit.']]},
  {slug:'ddr4-vs-ddr5-compatibility',title:'DDR4 versus DDR5 compatibility',description:'Platform requirements and practical upgrade tradeoffs between memory generations.',sections:[['They are not interchangeable','DDR4 and DDR5 use different electrical designs and keying. A motherboard supports the generation it was designed for; adapters are not a normal upgrade path.'],['Capacity and workload come first','Enough capacity usually matters before modest speed differences. Application performance also depends on CPU architecture, timings, channels, ranks, and workload.'],['Price the whole platform','A memory-generation change can require a motherboard and sometimes a CPU. Compare the full platform cost, available capacity, stability, and future upgrade options.']]},
  {slug:'ram-capacity-dual-channel-mixed-kits',title:'RAM capacity, channels, and mixed kits',description:'How module layout affects capacity, bandwidth, and stability.',sections:[['Capacity solves pressure','When active memory use exceeds installed RAM, the system relies more on storage and responsiveness can drop. Choose capacity from real workload use plus sensible headroom.'],['Channels increase aggregate bandwidth','Matched modules in the motherboard’s recommended slots can enable multi-channel operation. Consult the board manual because slot order matters.'],['Mixed kits carry uncertainty','Even kits with the same retail name can use different components. Mixing changes validation conditions and may require lower speeds or looser timings; matched kits are easier to support.']]},
  {slug:'m2-nvme-sata-explained',title:'M.2, NVMe, and SATA explained',description:'Form factor, protocol, and interface are different parts of an SSD description.',sections:[['M.2 describes a form factor','An M.2 device has a compact card shape, but the slot can carry PCIe/NVMe, SATA, USB, or other signals depending on the board. Keying and length also vary.'],['NVMe is a storage protocol','NVMe normally communicates over PCI Express. SATA uses the AHCI ecosystem and may appear as a 2.5-inch drive or an M.2 module.'],['Check the board manual','Confirm supported protocol, key, module length, lane generation, boot support, cooling, and whether using the slot disables another connector or expansion slot.']]},
  {slug:'pcie-generations-lanes-shared-slots',title:'PCIe generations, lanes, and shared slots',description:'How link width, generation, and motherboard lane sharing affect expansion devices.',sections:[['A link has generation and width','Each PCIe generation changes per-lane throughput. An x16-shaped slot may be wired for fewer lanes, and devices normally negotiate a mutually supported link.'],['Lanes can be shared','Consumer platforms divide CPU and chipset lanes among graphics, storage, networking, and other controllers. Installing an M.2 drive can reduce another slot or disable a SATA port.'],['Read the configuration table','Motherboard manuals document lane-sharing cases. Check the exact CPU too, because available lanes and generations can change with the installed processor.']]},
  {slug:'ssd-endurance-tbw-sustained-writes',title:'SSD endurance, TBW, and sustained writes',description:'How to interpret flash endurance and write performance for your workload.',sections:[['TBW is a warranty rating','Terabytes written states an allowed write volume under the warranty terms. It is not a countdown to immediate failure and should be compared for the exact capacity.'],['Burst speed is not sustained speed','A drive may write quickly to a cache, then slow during a long transfer. Controller, NAND type, temperature, free space, and workload determine sustained behavior.'],['Match evidence to use','Everyday systems, video scratch disks, databases, and write-heavy workstations have different needs. Check independent sustained tests, warranty terms, power-loss behavior, and backup strategy.']]},
  {slug:'pc-compatibility-checklist',title:'PC compatibility checklist before buying',description:'A practical final review for sockets, memory, power, cooling, storage, and physical fit.',sections:[['Platform','Confirm CPU support and BIOS, motherboard form factor, memory generation and module support, cooler mounting, and operating-system requirements.'],['Power and fit','Check PSU capacity and connectors, GPU and cooler dimensions, case clearances, radiator conflicts, airflow, and front-panel connections.'],['Storage and expansion','Confirm M.2 protocol and size, SATA sharing, PCIe lane configuration, expansion-slot spacing, rear I/O, networking, display outputs, and enough ports. Recheck exact model numbers on manufacturer pages before ordering.']]}
];
const guideIcons={
 gpu:`<svg viewBox="0 0 64 64" fill="none"><rect x="8" y="16" width="48" height="32" rx="7"/><circle class="guide-icon-spin" cx="25" cy="32" r="9"/><circle class="guide-icon-spin guide-icon-spin-delay" cx="45" cy="32" r="7"/><path d="M13 48v5m8-5v5M56 26h4m-4 10h4"/></svg>`,
 cpu:`<svg viewBox="0 0 64 64" fill="none"><rect x="17" y="17" width="30" height="30" rx="6"/><rect class="guide-icon-pulse" x="25" y="25" width="14" height="14" rx="3"/><path d="M23 9v8m9-8v8m9-8v8M23 47v8m9-8v8m9-8v8M9 23h8m-8 9h8m-8 9h8m30-18h8m-8 9h8m-8 9h8"/></svg>`,
 ram:`<svg viewBox="0 0 64 64" fill="none"><rect x="7" y="20" width="50" height="24" rx="5"/><path class="guide-icon-slide" d="M15 27h10v10H15zm14 0h9v10h-9zm13 0h7v10h-7z"/><path d="M16 44v6m8-6v6m16-6v6m8-6v6"/></svg>`,
 ssd:`<svg viewBox="0 0 64 64" fill="none"><rect x="8" y="23" width="48" height="18" rx="7"/><circle cx="15" cy="32" r="2"/><path class="guide-icon-slide" d="M23 29h21m-21 6h14"/><path d="M56 28h4v8h-4"/></svg>`
};
const guideIcon=cat=>`<span class="guide-icon" data-guide-icon="${cat}" aria-hidden="true">${guideIcons[cat]}</span>`;
write('learn',shell('Hardware guides','learn',`${heading('Understand your hardware.','Practical guides to compatibility, specifications, and sensible comparisons.')}<div class="guide-grid">${guides.map((g,i)=>`<a class="guide-card" href="/learn/${g.cat}/"><span class="guide-card-top"><span class="guide-number">0${i+1}</span>${guideIcon(g.cat)}</span><h2>${g.title}</h2><p>${g.subtitle}</p><span class="guide-link">Read guide ${arrow}</span></a>`).join('')}</div><section class="article-library"><div class="section-heading"><div><h2>Compatibility and buying guides</h2><p>Detailed checks for the decisions a spec table cannot make for you.</p></div></div><div class="guide-grid">${articles.map((a,i)=>`<a class="guide-card" href="/learn/articles/${a.slug}/"><span class="guide-number">${String(i+5).padStart(2,'0')}</span><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p><span class="guide-link">Read article ${arrow}</span></a>`).join('')}</div></section><div class="library-callout"><div><h2>Looking for a specific model?</h2><p>Every catalog entry has its own specification page and source links.</p></div><a class="button secondary" href="/hardware/">Find hardware ${arrow}</a></div>${adSlot('native')}`,{canonicalPath:'/learn/',description:'Understand PC hardware specifications, compatibility, and comparison limits with practical CPU, GPU, memory, and storage guides.'}));
for(const g of guides)write('learn/'+g.cat,shell(g.title+' guide','guide',`<a class="back-link" href="/learn/">← Hardware guides</a>${heading(g.title+'.',g.subtitle,`<span class="guide-heading-icon">${guideIcon(g.cat)}</span>`)}<div class="guide-reading"><div class="guide-terms">${g.terms.map(([term,explanation],i)=>`<section><span class="guide-term-number">0${i+1}</span><div><h2>${term}</h2><p>${explanation}</p></div></section>`).join('')}<section><span class="guide-term-number">04</span><div><h2>How to compare responsibly</h2><p>Start with the workload and platform, verify the exact model, and use application or game tests collected under comparable conditions. Specifications explain capabilities and constraints; they do not predict an exact result by themselves.</p></div></section>${adSlot('responsive')}</div><aside><p>Put the specifications side by side.</p><a class="button primary" href="/compare/?category=${g.cat}">Compare ${g.title.toLowerCase()} ${arrow}</a><a class="subtle-link" href="/hardware/${categoryPaths[g.cat]}/">Browse ${g.title.toLowerCase()} →</a></aside></div>${adSlot('native')}`,{canonicalPath:`/learn/${g.cat}/`,description:`A practical guide to ${g.title.toLowerCase()} specifications, compatibility, and the limits of spec-sheet comparisons.`,schema:{'@context':'https://schema.org','@type':'Article',headline:`${g.title} guide`,description:g.subtitle,mainEntityOfPage:SITE+`/learn/${g.cat}/`,author:{'@type':'Organization',name:'PC Part Performance'},publisher:{'@type':'Organization',name:'PC Part Performance'}}}));
for(const article of articles){const canonicalPath=`/learn/articles/${article.slug}/`;write('learn/articles/'+article.slug,shell(article.title,'article',`<a class="back-link" href="/learn/">← Hardware guides</a>${heading(article.title+'.',article.description)}<div class="reading-layout"><article>${article.sections.map(([title,copy],i)=>`<section><span class="eyebrow">${String(i+1).padStart(2,'0')}</span><h2>${esc(title)}</h2><p>${esc(copy)}</p></section>${i===0?adSlot('responsive'):''}`).join('')}<h2>Sources and verification</h2><p>Use the exact product manuals and support lists linked from each catalog record. Industry specifications are maintained by organizations such as <a href="https://pcisig.com/" target="_blank" rel="noopener">PCI-SIG</a>, <a href="https://www.jedec.org/" target="_blank" rel="noopener">JEDEC</a>, and <a href="https://nvmexpress.org/" target="_blank" rel="noopener">NVM Express</a>. Product implementations can be narrower than an industry standard.</p></article><aside><p>Apply the checklist to real parts.</p><a class="button primary" href="/builder/">Open PC builder ${arrow}</a><a class="subtle-link" href="/compare/">Compare hardware →</a></aside></div>${adSlot('native')}`,{canonicalPath,description:article.description,schema:{'@context':'https://schema.org','@type':'Article',headline:article.title,description:article.description,mainEntityOfPage:SITE+canonicalPath,author:{'@type':'Organization',name:'PC Part Performance'},publisher:{'@type':'Organization',name:'PC Part Performance'}}}));}

write('builder',shell('PC builder','builder',`<section id="builder" class="builder" aria-labelledby="builder-title"><div class="builder-heading"><div><h1 id="builder-title">Build your PC.</h1><p>Select your parts. Check how they fit together.</p></div><div class="builder-actions"><button class="button secondary" id="builder-clear">Clear build</button><button class="button primary" id="builder-starter">Load starter build ${arrow}</button></div></div><div class="builder-toolbar"><label class="compat-toggle"><input id="enable-incompatible" type="checkbox"><span><strong>Show incompatible parts</strong></span></label><span id="builder-filter-status">Compatible parts</span></div><div class="builder-shell"><div class="builder-parts"><div class="builder-column-head"><span>Components</span><span>Select a part to get started</span></div><div id="builder-parts"></div></div><div class="builder-rail"><aside class="builder-analysis" aria-live="polite"><div id="build-verdict"></div><details class="analysis-block" open><summary>Compatibility checks</summary><div id="build-checks"></div></details><details class="analysis-block"><summary>System specifications</summary><div id="build-specs"></div></details><details class="analysis-block"><summary>Hardware outlook</summary><div id="build-performance"></div></details></aside><details class="assembly-details"><summary>Assembly diagram</summary><section class="pc-visual-panel" aria-labelledby="pc-visual-title"><div class="pc-visual-head"><div><h3 id="pc-visual-title">Illustrative placement</h3><p>Positions are approximate.</p></div><span id="pc-visual-count">0 installed</span></div><div id="pc-visual" class="pc-visual"></div><div id="pc-visual-status" class="pc-visual-status"></div></section></details></div></div><p class="builder-limit">Confirm exact dimensions, cooling, BIOS, and connectors with the manufacturer. <a href="/methodology/#compatibility">What we check →</a></p></section>${adSlot('responsive')}`,{canonicalPath:'/builder/',description:'Select PC parts and check indexed socket, memory, storage, slot, and power compatibility before verifying exact manufacturer requirements.'}));

write('methodology',shell('Data and photo sources','methodology',`${heading('Data you can trace.','What the numbers and photos represent.')}<div class="method-grid"><details open><summary>Specifications & missing data</summary><p>Each part links to its source. Charts use a shared unit and start at zero. A dash means unavailable, not zero. Product names, years, and specifications come from the existing catalog; source availability can change.</p></details><details><summary>Benchmarks & game performance</summary><p>Specifications do not measure game FPS. PassMark G3D values, where available, are an inherited September 12, 2026 snapshot from <a href="https://www.videocardbenchmark.net/" target="_blank" rel="noopener">PassMark</a>. They aggregate different systems. This catalog has no matched game FPS dataset.</p></details><details id="compatibility"><summary>PC compatibility checks</summary><p>The builder checks indexed sockets, memory, storage ports, slots, and power. Its estimate adds CPU TDP, GPU board power, and 100 W, then adds a 25% margin. Verify BIOS, dimensions, cooling, and exact connectors separately. Hardware outlooks are estimates, not benchmarks.</p></details><details><summary>Product & reference photos</summary><p>Official product photos come from the manufacturer and show the selected model. Other product photos show a verified model or partner card. Family photos show a related capacity or variant. Reference photos illustrate a related component and identify the actual model pictured; they do not verify the selected part’s appearance. Sources are available on each part page and below comparisons.</p></details></div>`,{canonicalPath:'/methodology/',description:'How PC Part Performance sources specifications and photos, handles missing data, and checks indexed PC compatibility.'}));

for(const p of records){const a=images[p.id],specs=Object.entries(p.specs),canonicalPath=`/learn/${encodeURIComponent(p.id)}.html`;const content=`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/hardware/">Hardware</a><span aria-hidden="true">/</span><a href="${categoryPaths[p.cat]?'/hardware/'+categoryPaths[p.cat]+'/':'/hardware/?category='+p.cat}">${esc(groupName(p.cat))}</a><span aria-hidden="true">/</span><span>${esc(p.name)}</span></nav><section class="part-hero"><div class="part-visual">${picture(p,'',true)}</div><div class="part-title"><span class="part-brand">${esc(p.brand)}</span><h1>${esc(p.name)}</h1><p>${esc(p.summary)}</p><div class="part-tags"><span>${esc(p.architecture)}</span>${p.year?`<span>${p.year}</span>`:''}</div><a class="button primary magnetic" href="/compare/?parts=${encodeURIComponent(p.id)}">Compare this part ${arrow}</a></div></section><div class="record-detail"><div><h2>Specifications</h2>${specs.length?`<table><tbody>${specs.map(([k,v])=>`<tr><th scope="row">${esc(k)}</th><td>${esc(v)}${context.unitMap[k]?' '+esc(context.unitMap[k]):''}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Detailed specifications are not indexed for this part.</p>'}${adSlot('rectangle')}</div><aside><h2>Model notes</h2><p>${esc(p.note||'Reference specifications. Partner models and exact configurations may differ.')}</p><a class="source-link" href="${esc(p.source)}" target="_blank" rel="noopener">Specification source ${arrow}</a>${a?`<details class="photo-attribution"><summary>About this photo</summary><p>${a.official&&a.kind==='exact'?'Official product photo':a.kind==='exact'?'Product photo':a.kind==='family'?'Product family photo':'Reference photo'}: ${esc(a.picturedModel)}.</p>${a.kind!=='exact'?'<p>The selected variant may look different.</p>':''}<a href="${esc(a.sourceUrl)}" target="_blank" rel="noopener">Photo source ${arrow}</a>${creditLine(a)}</details>`:''}</aside></div>`;fs.writeFileSync(path.join(root,'learn',p.id+'.html'),shell(p.name,'record',content,{canonicalPath,description:`${p.name}: ${p.summary}. Specifications, model notes, photos, and comparisons.`,schema:{'@context':'https://schema.org','@type':'Product',name:p.name,brand:{'@type':'Brand',name:p.brand},description:p.summary,url:SITE+canonicalPath}}));pageUrls.add(canonicalPath);}

write('privacy',shell('Privacy and advertising choices','privacy',`${heading('Privacy and advertising choices.','How this site handles preferences and third-party advertising.')}<div class="reading-layout"><article><h2>Advertising</h2><p>Selected pages may show advertisements supplied by Adsterra and its advertising partners. Their code loads only after you choose Accept ads. It may receive device, browser, page-view, cookie, IP-derived location, and interaction data under the partner’s policies to deliver, secure, and measure ads.</p><h2>Your choice</h2><p>Declining advertising does not remove any site feature. Your choice is stored on this device. Use the Ad choices button in the footer to revisit it. Revoking consent prevents future ad loads; it cannot recall requests already sent before revocation.</p><h2>Site data</h2><p>Theme and comparison preferences can be stored locally in your browser. This site does not require an account. External specification, photo, font, hosting, and advertising providers receive normal web requests when their resources are used.</p><h2>Advertising design</h2><p>Ads are labeled, kept away from controls, and displayed inside restricted frames. The site does not use popups, automatic redirects, interstitials, autoplay audio, or notification prompts.</p></article><aside><p>Manage your choice at any time.</p><button class="button secondary manage-ads" type="button">Open ad choices</button><a class="subtle-link" href="https://adsterra.com/privacy-policy/" target="_blank" rel="noopener">Advertising partner privacy policy →</a></aside></div>`,{canonicalPath:'/privacy/',description:'Privacy information and advertising choices for PC Part Performance.'}));
const logoPaths=mark.match(/<svg[^>]*>(.*)<\/svg>/)[1];
fs.writeFileSync(path.join(root,'assets/logo.svg'),`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40" fill="none" color="#c2ed78">${logoPaths}</svg>`);
fs.writeFileSync(path.join(root,'assets/favicon.svg'),`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" fill="none"><rect width="48" height="48" rx="14" fill="#151a13"/><g transform="translate(4 4)" color="#c2ed78">${logoPaths}</g></svg>`);
fs.writeFileSync(path.join(root,'404.html'),shell('Page not found','not-found',`<section class="not-found"><span class="error-number">404</span><h1>That page is missing.</h1><p>Try the hardware catalog or start a new comparison.</p><div><a class="button primary" href="/hardware/">Find hardware ${arrow}</a><a class="button secondary" href="/">Back home</a></div></section>`,{canonicalPath:'/404.html',indexable:false}));
fs.writeFileSync(path.join(root,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /ads/\nSitemap: ${SITE}/sitemap.xml\n`);
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${[...pageUrls].sort().map(url=>`  <url><loc>${SITE}${url}</loc></url>`).join('\n')}\n</urlset>\n`);
console.log(`Generated ${records.length} part pages, four category pages, four guides, and shared pages.`);
