const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve('dist');
const original=fs.readFileSync('dist/core.js','utf8');
const core=original;
fs.writeFileSync(path.join(root,'core.js'),core);
const context={window:{},document:{querySelector(){return null}}};vm.createContext(context);
for(const file of ['data.js','history-data.js','universe-data.js','component-data.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context);
vm.runInContext(core+';globalThis.records=catalog;globalThis.unitMap=units;',context);
const records=context.records;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mark='<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M5 23V13h5v10zm8 0V5h5v18zm8 0V9h5v14z" fill="currentColor"/></svg>';
function shell(title,route,body,extra='') {return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · PC Part Performance</title><meta name="description" content="Compare PC hardware side by side. Explore real specifications, find your next upgrade, and build a compatible PC."><meta name="theme-color" content="#101211"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><script src="/theme.js"></script>${route==='builder'?'<link rel="stylesheet" href="/builder-legacy.css">':''}<link rel="stylesheet" href="/design.css">${['data','history-data','universe-data','component-data','core','interface'].map(f=>`<script src="/${f}.js" defer></script>`).join('')}${extra}</head><body data-page="${route}"><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="PC Part Performance home"><span class="brand-mark">${mark}</span><span>PC Part<span class="brand-sub">Performance</span></span></a><nav aria-label="Main navigation">${[['compare','Compare'],['hardware','Hardware'],['builder','PC builder'],['learn','Learn']].map(([id,label])=>`<a href="/${id}/" ${route===id?'aria-current="page"':''}>${label}</a>`).join('')}</nav><button class="theme-toggle" aria-label="Switch color theme" title="Switch color theme"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M20.6 13.2A9 9 0 0 1 10.8 3.4a9 9 0 1 0 9.8 9.8Z"/></svg><span class="theme-label">Theme</span></button></header><main id="main">${body}</main><footer class="site-footer"><a href="/">PC Part Performance<span>Choose with clarity.</span></a><div><a href="/compare/">Compare</a><a href="/builder/">Build a PC</a><a href="/methodology/">Data & sources</a><span>© 2026</span></div></footer><div id="toast" role="status" aria-live="polite"></div><dialog id="part-picker" aria-labelledby="picker-title"><div class="dialog-top"><h2 id="picker-title">Choose hardware</h2><button class="icon-button" id="close-picker" aria-label="Close hardware picker">×</button></div><input type="search" id="picker-query" placeholder="Search a model or brand…" aria-label="Search hardware"><div id="picker-results"></div></dialog></body></html>`;}
function write(route,html){const dir=path.join(root,route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);}
write('',shell('Compare hardware. Find your next upgrade.','home',`<section class="home-hero"><div class="hero-copy"><span class="eyebrow">LESS GUESSWORK. BETTER BUILDS.</span><h1>Know your<br>next <span>upgrade.</span></h1><p>Compare hardware. See the differences.<br>Find the right parts for your PC.</p><a class="button primary" href="/compare/">Compare hardware <span aria-hidden="true">↗</span></a><a class="subtle-link" href="/builder/">Building from scratch? Start a PC build <span aria-hidden="true">→</span></a></div><a class="hero-matchup" href="/compare/?parts=rtx5070,rtx5060ti16" aria-label="Compare GeForce RTX 5070 and RTX 5060 Ti"><div class="matchup-top"><span>THE SIDE-BY-SIDE VIEW</span><span>01 / GPU</span></div><div class="hero-product first"><div><small>NVIDIA GEFORCE</small><strong>RTX 5070</strong><span>12 GB GDDR7</span></div><img src="/assets/rtx-5070.png" alt="ASUS Prime GeForce RTX 5070 graphics card" width="1725" height="493" fetchpriority="high"></div><span class="versus">VS</span><div class="hero-product second"><div><small>NVIDIA GEFORCE</small><strong>RTX 5060 Ti</strong><span>16 GB GDDR7</span></div><img src="/assets/rtx-5060-ti.png" alt="ASUS Dual GeForce RTX 5060 Ti graphics card" width="1725" height="430"></div><div class="matchup-bottom"><span>Two cards. The details that matter.</span><span class="round-arrow" aria-hidden="true">↗</span></div></a></section><section class="home-bottom"><div class="section-heading"><h2>Your next move.</h2><span class="muted">A clearer view of your hardware.</span></div><div class="quick-links"><a href="/compare/"><span class="quick-number">01</span><div><h3>Compare parts</h3><p>Real specs. Side by side.</p></div><span aria-hidden="true">↗</span></a><a href="/hardware/"><span class="quick-number">02</span><div><h3>Explore hardware</h3><p>${records.length.toLocaleString()} records. One searchable index.</p></div><span aria-hidden="true">↗</span></a><a href="/builder/"><span class="quick-number">03</span><div><h3>Build your PC</h3><p>Pick parts. Check compatibility.</p></div><span aria-hidden="true">↗</span></a></div></section>`));
write('compare',shell('Compare hardware','compare',`<div class="page-heading"><div><span class="eyebrow">THE COMPARISON WORKSPACE</span><h1>See the difference.</h1><p>Choose your hardware. Compare what matters.</p></div><button class="button secondary" id="export-csv">Export CSV <span aria-hidden="true">↓</span></button></div><div class="compare-controls"><div class="segmented" id="compare-categories" aria-label="Hardware category"></div><label class="more-category"><span class="sr-only">Other hardware categories</span><select id="more-category"><option value="">More hardware</option></select></label></div><section aria-label="Selected hardware" id="comparison-cards" class="comparison-cards"></section><div class="compare-options"><button class="text-button" id="add-comparison">＋ Add another part</button><label class="switch-label"><input type="checkbox" id="differences-only">Only differences</label></div><section class="comparison-data" aria-labelledby="overview-title"><div class="section-heading"><div><span class="eyebrow">AT A GLANCE</span><h2 id="overview-title">The key numbers.</h2></div><span class="source-caption">Reference specifications</span></div><div class="metric-grid" id="metric-grid"></div><p class="data-note">Specifications describe hardware, not game FPS. Partner models may differ.</p></section><section class="specifications"><div class="section-heading"><h2>Side by side.</h2><span class="muted" id="spec-count"></span></div><div class="table-scroll" id="comparison-table"></div><div id="comparison-warning"></div><details class="source-details"><summary>Sources & model notes</summary><div id="comparison-sources"></div></details></section>`));
const library=`<div class="page-heading"><div><span class="eyebrow">THE HARDWARE INDEX</span><h1>Find your next part.</h1><p>Browse specifications, explore models, and add them to a comparison.</p></div><span class="count-label">${records.length.toLocaleString()} records</span></div><div class="catalog-tools"><label class="search-field"><span aria-hidden="true">⌕</span><input id="catalog-search" type="search" placeholder="Search hardware…" aria-label="Search hardware"></label><select id="catalog-category" aria-label="Hardware category"></select><select id="catalog-era" aria-label="Release period"><option value="all">All generations</option><option value="modern">2020–present</option><option value="legacy">Before 2020</option></select><select id="catalog-sort" aria-label="Sort hardware"><option value="new">Newest first</option><option value="old">Oldest first</option><option value="name">Name A–Z</option></select></div><div class="catalog-meta"><span id="catalog-summary" aria-live="polite"></span><a class="subtle-link" href="/compare/" id="selected-link">Open comparison →</a></div><div class="table-scroll"><table class="hardware-table"><thead><tr><th>Hardware</th><th>Category</th><th>Year</th><th>Specification</th><th><span class="sr-only">Compare</span></th></tr></thead><tbody id="hardware-rows"></tbody></table></div><div class="empty-message" id="catalog-empty" hidden>No hardware matches. Try another name or category.</div><button class="button secondary load-more" id="catalog-more">Show more hardware</button>`;
write('hardware',shell('Hardware index','hardware',library));
write('learn',shell('Hardware library','learn',library.replace('Find your next part.','Get to know your hardware.').replace('THE HARDWARE INDEX','THE HARDWARE LIBRARY').replace('Browse specifications, explore models, and add them to a comparison.','Specifications and source notes for every part in the index.')));
let html=fs.readFileSync('scripts/builder-template.html','utf8');let builder=html.slice(html.indexOf('<section id="builder"'),html.indexOf('<section id="catalog"'));
builder=builder.replace('Build a compatible PC.','Make it your build.').replace('SYSTEM CONFIGURATOR','THE PC BUILDER').replace('Choose processors, graphics cards, memory and storage. The assembly view shows where each selected part installs while socket, slot, power and capacity checks update.','Choose your components. Check how they fit together.').replace('Enable incompatible components','Show incompatible parts').replace('<small>Show every indexed option</small>','').replace('Load a balanced build','Load starter build');
write('builder',shell('PC builder','builder',builder,'<script src="/builder-v2.js" defer></script>'));
write('methodology',shell('Data and sources','methodology',`<div class="page-heading"><div><span class="eyebrow">CLEAR NUMBERS. CLEAR CONTEXT.</span><h1>Behind the comparison.</h1><p>The useful details, without the guesswork.</p></div></div><div class="reading-layout"><article><h2>Specifications come first.</h2><p>Each hardware record links to its original source. Charts use the same unit and start at zero. Missing information stays unavailable; it never becomes a zero.</p><h2>Specs are not FPS.</h2><p>Memory, clock speeds, bandwidth and core counts describe hardware. They do not establish how fast a game runs. This catalog does not include a matched game FPS dataset.</p><h2>Benchmarks need context.</h2><p>Where available, PassMark G3D values are an inherited snapshot dated September 12, 2026, linked to <a href="https://www.videocardbenchmark.net/" target="_blank" rel="noopener">PassMark</a>. They aggregate different systems and are not directly controlled game comparisons.</p><h2>Compatibility has limits.</h2><p>The PC builder checks indexed sockets, memory, storage ports, slots and power. Its power estimate combines CPU TDP, GPU board power and a 100 W allowance, then adds a 25% margin. Check exact dimensions, cooling, BIOS and connectors with the manufacturer.</p><h2>Product photography.</h2><p>Featured RTX 5070 and RTX 5060 Ti photos show ASUS Prime and ASUS Dual models. Comparison values describe reference GPU specifications; partner card designs and clock speeds may differ. Image sources are linked below each comparison.</p></article><aside><strong>Need the source?</strong><p>Open “Sources & model notes” under any comparison.</p><a class="button primary" href="/compare/">Back to compare ↗</a></aside></div>`));
for(const p of records){const content=`<a class="back-link" href="/learn/">← Hardware library</a><div class="page-heading"><div><span class="eyebrow">${esc(p.brand)} · ${esc(p.cat.toUpperCase())}</span><h1>${esc(p.name)}</h1><p>${esc(p.architecture)}${p.year?' · '+p.year:''}</p></div><a class="button primary" href="/compare/?parts=${encodeURIComponent(p.id)}">Add to comparison ↗</a></div><div class="record-detail"><div><h2>Specifications</h2><table><tbody>${Object.entries(p.specs).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v)}${context.unitMap[k]?' '+esc(context.unitMap[k]):''}</td></tr>`).join('')}</tbody></table></div><aside><span class="eyebrow">MODEL NOTES</span><h2>${esc(p.summary)}</h2><p>${esc(p.note||'Reference specifications. Exact configurations and partner models may differ.')}</p><a class="subtle-link" href="${esc(p.source)}" target="_blank" rel="noopener">View original source ↗</a></aside></div>`;fs.writeFileSync(path.join(root,'learn',p.id+'.html'),shell(p.name,'record',content));}
fs.writeFileSync(path.join(root,'assets/favicon.svg'),`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#c4f564"/><path d="M5 23V13h5v10zm8 0V5h5v18zm8 0V9h5v14z" fill="#151914"/></svg>`);
console.log('Generated pages for '+records.length+' preserved hardware records.');
