const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),zlib=require('node:zlib');
const math=require('../dist/planning-math.js'),news=require('./news-policy.cjs'),ads=require('./ad-policy.cjs'),createAPI=require('./public-data-api.cjs');
const approx=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
const e=math.electricity({watts:200,hours:4,rate:.15});approx(e.kWh,.8);approx(e.annual,43.8);approx(math.electricity({watts:0,hours:0,rate:0}).annual,0);assert.throws(()=>math.electricity({watts:200,hours:25,rate:.1}));assert.throws(()=>math.electricity({watts:200,hours:4,rate:''}));
const budget=math.platform(Object.fromEntries(['a','b'].flatMap(k=>['cpu','board','ram','cooler','other'].map(f=>[k+f,k==='a'?100:200]))));assert.deepEqual(budget,{a:500,b:1000,difference:500});assert.throws(()=>math.platform({}));
approx(math.display({x:1920,y:1080,diagonal:24}).ppi,Math.hypot(1920,1080)/24);assert.throws(()=>math.display({x:1920,y:1080,diagonal:0}));
approx(math.recording({bitrate:8,hours:1,overhead:0}).gb,3.6);approx(math.recording({bitrate:8,hours:1,overhead:10}).gb,3.96);
approx(math.ai({parameters:8,bits:4,runtime:1,kv:2}).total,4e9/2**30+3);assert.throws(()=>math.ai({parameters:8,bits:4,runtime:'',kv:0}));assert.throws(()=>math.ai({parameters:'Infinity',bits:4,runtime:0,kv:0}));approx(math.frametime({fps:120,hz:144}).frame,1000/120);
assert.equal(math.lanes({m2:true,slot:false,cpu:'other'}).m2_3,'PCIe 4.0 ×4');assert.equal(math.lanes({m2:true,slot:true,cpu:'8500-8300'}).m2_3,'PCIe 4.0 ×2');assert.equal(math.lanes({m2:false,slot:true,cpu:'other'}).pci_e2,'PCIe 4.0 ×2');assert.match(math.lanes({cpu:'8500-8300'}).m2_2,/Unavailable/);
const phones=require('./phone-data.cjs');assert.deepEqual(math.phoneDifference(Object.fromEntries(Object.entries(phones[0].fields).map(([k,f])=>[k,f.value])),Object.fromEntries(Object.entries(phones[1].fields).map(([k,f])=>[k,f.value]))),{height:2,width:-.09999999999999432,depth:.4500000000000002,weight:29});for(const p of phones){assert.equal(p.fields.priceCAD.value,null);assert.equal(p.support.endDate,null);for(const f of Object.values(p.fields))if(f.value!==null){assert.ok(f.source.startsWith('https://'));assert.equal(f.checked,'2026-10-04')}}
const now=Date.parse('2026-10-04T12:00:00Z'),story={type:'news',route:'news/test-source',title:'A <story> & evidence',status:'published',editorApproved:true,confirmedDeployment:true,sourceIds:['msi'],datePublished:'2026-10-03T12:00:00Z'};assert.ok(news.eligible(story,now));assert.match(news.newsSitemap([story],now),/A &lt;story&gt; &amp; evidence/);assert.ok(!news.eligible({...story,datePublished:'2026-10-01T12:00:00Z'},now));assert.ok(!news.eligible({...story,datePublished:'2026-10-05T12:00:00Z'},now));assert.ok(!news.eligible({...story,status:'draft'},now));assert.ok(!news.eligible({...story,confirmedDeployment:false},now));assert.equal(news.newsArticle(story)['@type'],'NewsArticle');assert.throws(()=>news.newsArticle({...story,editorApproved:false}));const q=news.queueEntry({source:'official',title:'Release',url:'https://example.com/release',sourcePublishedAt:'2026-10-01'},'2026-10-04');assert.equal(q.id,news.queueEntry({source:'official',title:'Different title',url:'https://example.com/release'}).id);assert.equal(q.datePublished,null);assert.throws(()=>news.queueEntry({source:'bad',title:'Bad',url:'http://127.0.0.1/'}));
assert.equal(ads.mayRequestAds({consent:true}),false);const settings={...ads.config,enabled:true,publisherApproved:true,cmpVerified:true,publisherId:'ca-pub-1234567890123456'};assert.ok(ads.mayRequestAds({settings,consent:true,pageKind:'article'}));assert.ok(!ads.mayRequestAds({settings,consent:true,gpc:true,pageKind:'article'}));assert.ok(!ads.mayRequestAds({settings,consent:true,pageKind:'builder'}));assert.ok(!ads.mayRequestAds({settings,consent:false,pageKind:'article'}));
let time=100000;const api=createAPI({root:path.resolve('dist'),limit:2,windowMs:60000,now:()=>time});function request(url,method='GET',ip='test',headers={}){const res={code:0,headers:null,body:null,writeHead(code,h){this.code=code;this.headers=h},end(body){this.body=body}};assert.ok(api({url,method,socket:{remoteAddress:ip},headers},res));return res}const first=request('/api/v1/phones');assert.equal(first.code,200);assert.equal(JSON.parse(first.body).phones.length,phones.length);assert.equal(request('/api/v1/phones','HEAD').body,undefined);assert.equal(request('/api/v1/phones').code,429);time+=60000;assert.equal(request('/api/v1/phones','GET','test',{'if-none-match':first.headers.ETag}).code,304);assert.equal(request('/api/v1/unknown').code,404);assert.equal(request('/api/v1/phones','POST').code,405);
const manifest=JSON.parse(fs.readFileSync('docs/stage2/manifest.json')),sitemap=fs.readFileSync('dist/sitemap.xml','utf8');for(const p of manifest.newPages){const html=fs.readFileSync(path.join('dist',p.route,'index.html'),'utf8');if(p.noindex){assert.match(html,/content="noindex,follow"/);assert.ok(!sitemap.includes('https://www.pcpartperformance.com'+p.route))}else assert.ok(sitemap.includes('https://www.pcpartperformance.com'+p.route));assert.ok(!html.includes('interface.js'));assert.ok(!html.includes('adsbygoogle'));if(p.image){const png=fs.readFileSync(path.join('dist',p.image.src));assert.equal(png.readUInt32BE(16),1200);assert.equal(png.readUInt32BE(20),675)}assert.ok(!html.includes('"@type":"NewsArticle"'))}
for(const a of manifest.articles){assert.ok(a.wordCount>=350,a.slug+' lacks substantive text');assert.equal(a.datePublished,null)}
const rows=JSON.parse(fs.readFileSync('dist/data/search-index.json'));assert.equal(new Set(rows.map(r=>r.id)).size,rows.length);for(const row of rows){assert.match(row.url,/^\/[a-zA-Z0-9_/.\-]+$/);assert.ok(fs.existsSync(path.join('dist',row.url)))}
const report={checked:new Date().toISOString(),newPages:manifest.newPages.length,guides:manifest.articles.length,tools:manifest.tools.length,phones:manifest.phones,jsGzipBytes:Object.fromEntries(['planning-math.js','publication-ui.js'].map(f=>[f,zlib.gzipSync(fs.readFileSync(path.join('dist',f))).length])),checks:['Calculator arithmetic, boundaries, blanks and unit conversion','MSI sharing and CPU restriction','Per-field phone evidence and unknowns','News review/deployment gates, future dates, two-day aging and deduplication','Default-off ad/consent/GPC gates','Optional API GET/HEAD/ETag/404/405/429 and rate-window expiry','Draft/saved/search exclusions; sitemap; 1200px images; substantive guides; no full catalog JS on new pages','Unique search IDs and safe local result paths']};fs.writeFileSync('docs/stage2/validation.json',JSON.stringify(report,null,2));console.log(report);
