const articles=require('./feature-articles.cjs');
module.exports=({esc})=>{
 const cards=`<section class="learn-features" aria-labelledby="practical-guides"><h2 id="practical-guides">Build and upgrade guides</h2><div class="feature-list">${articles.map(a=>`<article><span class="section-label">${esc(a.category)}</span><h3><a href="/learn/${a.slug}/">${esc(a.title)}</a></h3><p>${esc(a.description)}</p><a class="article-read" href="/learn/${a.slug}/">Read guide<span class="sr-only">: ${esc(a.title)}</span></a></article>`).join('')}</div></section>`;
 const render=a=>{
 const url=`https://www.pcpartperformance.com/learn/${a.slug}/`;
 const schema={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:a.title,description:a.description,mainEntityOfPage:url,author:{'@type':'Organization',name:'PC Part Performance',url:'https://www.pcpartperformance.com/'},publisher:{'@type':'Organization',name:'PC Part Performance'},articleSection:a.category},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Learn',item:'https://www.pcpartperformance.com/learn/'},{'@type':'ListItem',position:2,name:a.title,item:url}]}]};
 return `<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><nav class="article-breadcrumb" aria-label="Breadcrumb"><a href="/learn/">Hardware guides</a><span aria-hidden="true">/</span><span>${esc(a.category)}</span></nav><header class="article-header"><span class="section-label">${esc(a.category)}</span><h1>${esc(a.title)}</h1><p>${esc(a.description)}</p><div class="article-byline">By PC Part Performance</div></header><div class="article-layout"><nav class="article-toc" aria-label="On this page"><strong>On this page</strong>${a.sections.map((s,i)=>`<a href="#section-${i}">${esc(s[0])}</a>`).join('')}<a href="#watch">Watch the walkthrough</a><a href="#sources">Sources</a></nav><article class="article-copy">${a.sections.map((s,i)=>`<section id="section-${i}"><h2>${esc(s[0])}</h2>${s.slice(1).map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('')}<section class="article-video" id="watch"><span class="section-label">Watch on YouTube</span><h2>${esc(a.video[1])}</h2><p>${esc(a.video[2])}. A companion video for readers who prefer a visual walkthrough.</p><a class="button secondary" href="${esc(a.video[0])}" target="_blank" rel="noopener noreferrer">Watch video <span class="sr-only">on YouTube (opens a new tab)</span></a></section><section id="sources"><h2>Sources and further reading</h2><ul class="article-sources">${a.sources.map(s=>`<li><a href="${esc(s[1])}" target="_blank" rel="noopener noreferrer">${esc(s[0])}</a></li>`).join('')}</ul></section><section class="article-next"><h2>Put it into practice</h2><a class="button primary" href="${a.next[0]}">${esc(a.next[1])}</a></section><nav class="related-guides" aria-label="Related articles"><h2>Keep reading</h2>${articles.filter(b=>b!==a).map(b=>`<a href="/learn/${b.slug}/">${esc(b.title)}</a>`).join('')}</nav></article></div>`;
 };
 return {articles,cards,render};
};
