const articles=[...require('./feature-articles.cjs'),...require('./blog-additions.cjs'),...require('./ai-articles.cjs')];
articles.find(a=>a.slug==='cpu-or-gpu-upgrade-for-gaming').video[2]='Mostly Positive Reviews';
const answers={'pc-build-compatibility-checklist':'Check the CPU support list and BIOS, then verify memory, storage connections, power cables and the physical space for the exact parts. A socket match alone is not a complete compatibility check.','how-to-choose-gaming-ram':'Match the DDR generation and supported kit to your platform, then choose capacity around your real workload. Extra capacity and a faster memory profile solve different problems.','cpu-or-gpu-upgrade-for-gaming':'Test the games and settings you use. If reducing resolution substantially improves frame rate, investigate the GPU; if it does not, check CPU-side limits and frame caps before choosing an upgrade.'};
for(const a of articles){a.answer ||= answers[a.slug]||a.description;a.citations ||= a.category==='Memory'?{0:[0],2:[0],3:[1]}:a.category==='Gaming performance'?{0:[0],2:[1]}:{1:[0],4:[1]};}
module.exports=({esc})=>{
 const cards=`<section class="learn-features" aria-labelledby="practical-guides"><h2 id="practical-guides">Hardware guides and AI explainers</h2><div class="feature-list">${articles.map(a=>`<article><span class="section-label">${esc(a.category)}</span><h3><a href="/blog/${a.slug}/">${esc(a.title)}</a></h3><p>${esc(a.description)}</p><a class="article-read" href="/blog/${a.slug}/">Read article<span class="sr-only">: ${esc(a.title)}</span></a></article>`).join('')}</div></section>`;
 const render=a=>{
 const url=`https://www.pcpartperformance.com/blog/${a.slug}/`;
 const schema={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:a.title,description:a.description,...(a.image?{image:'https://www.pcpartperformance.com'+a.image.src}:{}),mainEntityOfPage:url,author:{'@type':'Organization',name:'PC Part Performance',url:'https://www.pcpartperformance.com/about/'},publisher:{'@type':'Organization',name:'PC Part Performance'},articleSection:a.category,datePublished:'2026-09-18',dateModified:'2026-09-18'},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Blog',item:'https://www.pcpartperformance.com/blog/'},{'@type':'ListItem',position:2,name:a.title,item:url}]}]};
 return `<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><nav class="article-breadcrumb" aria-label="Breadcrumb"><a href="/blog/">Blog</a><span aria-hidden="true">/</span><span>${esc(a.category)}</span></nav><header class="article-header"><span class="section-label">${esc(a.category)}</span><h1>${esc(a.title)}</h1><p>${esc(a.description)}</p><div class="article-byline">By <a href="/about/">PC Part Performance</a> · <time datetime="2026-09-18">September 18, 2026</time></div></header><div class="article-layout"><nav class="article-toc" aria-label="On this page"><strong>On this page</strong>${a.sections.map((s,i)=>`<a href="#section-${i}">${esc(s[0])}</a>`).join('')}<a href="#watch">Watch the walkthrough</a><a href="#sources">Sources</a></nav><article class="article-copy"><div class="article-answer"><strong>The short answer</strong><p>${esc(a.answer)}</p></div>${a.image?`<figure class="article-diagram"><img src="${a.image.src}" alt="${esc(a.image.alt)}" width="1200" height="675" loading="lazy" decoding="async"></figure>`:''}${a.table?`<div class="article-table-wrap" tabindex="0" role="region" aria-label="${esc(a.table.caption)}"><table class="article-table"><caption>${esc(a.table.caption)}</caption><thead><tr>${a.table.headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${a.table.rows.map(row=>`<tr>${row.map((cell,j)=>j?`<td>${esc(cell)}</td>`:`<th scope="row">${esc(cell)}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`:''}${a.sections.map((s,i)=>`<section id="section-${i}"><h2>${esc(s[0])}</h2>${s.slice(1).map(p=>`<p>${esc(p)}</p>`).join('')}${(a.citations[i]||[]).map(n=>`<p class="inline-source"><a href="${esc(a.sources[n][1])}" target="_blank" rel="noopener noreferrer">Source: ${esc(a.sources[n][0])}</a></p>`).join('')}</section>`).join('')}<section class="article-video" id="watch"><span class="section-label">Watch on YouTube</span><h2>${esc(a.video[1])}</h2><p>${esc(a.video[2])}. Manufacturer or independent companion video; the creator’s views are their own.</p><a class="button secondary" href="${esc(a.video[0])}" target="_blank" rel="noopener noreferrer">Watch video <span class="sr-only">on YouTube (opens a new tab)</span></a></section><section id="sources"><h2>Sources and further reading</h2><ul class="article-sources">${a.sources.map(s=>`<li><a href="${esc(s[1])}" target="_blank" rel="noopener noreferrer">${esc(s[0])}</a></li>`).join('')}</ul></section><section class="article-next"><h2>Put it into practice</h2><a class="button primary" href="${a.next[0]}">${esc(a.next[1])}</a></section><nav class="related-guides" aria-label="Related articles"><h2>Keep reading</h2>${articles.filter(b=>b!==a).sort((x,y)=>(y.category===a.category)-(x.category===a.category)).slice(0,4).map(b=>`<a href="/blog/${b.slug}/">${esc(b.title)}</a>`).join('')}</nav></article></div>`;
 };
 return {articles,cards,render};
};
