const fs=require('node:fs'),path=require('node:path'),models=require('./phone-models.json'),phones=require('./phone-data.cjs');
module.exports=({root,images,esc})=>{
 const data=Object.values(models);fs.writeFileSync(path.join(root,'data/phone-models.json'),JSON.stringify(data));
 const photo=p=>{const m=models[p.id],a=images[(m?.ids||[p.id,...(p.id==='pixel-9-pro'?['pixel9pro']:[])]).find(id=>images[id])];return a?`<figure><img src="${esc(a.src)}" alt="${esc(a.picturedModel)}" width="${a.width||800}" height="${a.height||500}" loading="lazy" decoding="async"></figure>`:`<figure><svg viewBox="0 0 75 155" role="img" aria-label="${esc(p.name)} body outline"><rect x="2" y="2" width="71" height="151" rx="9" fill="none" stroke="currentColor" stroke-width="2"/></svg></figure>`};
 const cards=ids=>`<section class="phone-comparison-views" aria-label="Phone viewing angles">${ids.map(id=>{const p=phones.find(p=>p.id===id);return `<article class="phone-comparison-item"><h2>${esc(p.name)}</h2><div data-phone-preview="${esc(id)}">${photo(p)}</div></article>`}).join('')}</section>`;
 const phoneOptions=html=>html.replace(/<option value="([^"]+)"/g,(match,id)=>{const p=phones.find(p=>p.id===id);if(!p)return match;const brand=id.startsWith('iphone-')?'Apple':id.startsWith('pixel-')?'Google':id.startsWith('galaxy-')?'Samsung':'OnePlus';const m=models[id],a=images[(m?.ids||[id,...(id==='pixel-9-pro'?['pixel9pro']:[])]).find(alias=>images[alias])];return `${match} data-has-model="${Boolean(m)}" data-brand="${brand}"${a?` data-image="${esc(a.src)}"`:''}`});
 const scripts='<link rel="stylesheet" href="/phone-preview.css"><script src="/phone-preview.js?v=20261004d" defer></script>';
 const edit=(route,fn)=>{const file=path.join(root,route,'index.html');let html=fs.readFileSync(file,'utf8');html=fn(html).replace('</head>',scripts+'</head>');fs.writeFileSync(file,html)};
 for(const p of phones)edit('phones/'+p.id,html=>html.replace(/<div class="phone-preview">[\s\S]*?<\/div>/,'').replace('<article class="publication-copy">',cards([p.id])+'<article class="publication-copy">'));
 for(const [a,b]of[['iphone-16','iphone-16-pro'],['iphone-16','pixel-9']])edit('phones/compare/'+a+'-vs-'+b,html=>html.replace('<article class="publication-copy">',cards([a,b])+'<article class="publication-copy">'));
 edit('phones/size-compare',html=>phoneOptions(html).replace('<div id="phone-design-view" data-phone-design></div>',`<div id="phone-design-view" data-phone-design><div data-phone-comparison>${cards(['iphone-16','pixel-9'])}</div></div><template data-phone-view-templates>${cards(phones.map(p=>p.id))}</template>`).replace('</head>','<link rel="stylesheet" href="/builder-refresh.css"><script src="/select-ui.js?v=20261004f" defer></script><script src="/phone-compare-ui.js?v=20261004d" defer></script></head>'));
 const creditFile=path.join(root,'builder/model-credits/index.html');let credit=fs.readFileSync(creditFile,'utf8');credit=credit.replace('<p class="data-note">Preview geometry',`<section id="phone-models"><h2>Phone models</h2>${data.map(m=>`<article class="source-details" style="padding:1.5rem;margin:1rem 0"><h3>${esc(m.name)}</h3><p><a href="${esc(m.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(m.title)}</a> by ${esc(m.creator)} · <a href="https://creativecommons.org/licenses/by/4.0/">${esc(m.license)}</a>.</p><p>Changes: deduplicated geometry, pruned unused nodes, Meshopt compression.${m.name==='Galaxy S25'?' One phone extracted from the two-instance scene.':''} ${esc(m.note||'Appearance preview; not a manufacturer-certified dimensional model.')}</p><a href="/phones/${Object.keys(models).find(k=>models[k]===m)}/">View phone</a></article>`).join('')}</section><p class="data-note">Preview geometry`);fs.writeFileSync(creditFile,credit);
};
