const fs=require('fs'),path=require('path'),crypto=require('crypto');
module.exports=({root,records,shell,write,esc})=>{
 const domain='https://www.pcpartperformance.com',articles=[...require('./feature-articles.cjs'),...require('./blog-additions.cjs'),...require('./ai-articles.cjs')];
 write('about',shell('About PC Part Performance and our editorial standards','about',`<header class="page-heading"><div><h1>About PC Part Performance</h1><p>Hardware specifications, practical build tools, and clearly sourced explanations.</p></div></header><article class="article-copy" style="max-width:760px;margin:32px auto"><h2>What we publish</h2><p>PC Part Performance helps readers compare hardware, plan a PC, and understand game performance. Our Blog publishes researched explainers and practical guides. Articles credited to PC Part Performance are site-produced editorial content, not a claim of an independent laboratory or named expert review.</p><h2>Evidence before claims</h2><p>We link to manufacturer documentation and relevant original testing. We distinguish published specifications, estimates, company forecasts and our analysis. A product being listed does not mean we tested it, and a 3D illustration does not certify fit.</p><h2>Dates and updates</h2><p>Publication dates identify when an article appeared. Modification dates change when we substantively revise content. Market articles state the dates of their evidence; they are not continuously updated price feeds.</p><h2>Buying information</h2><p>Retailer links may be searches rather than exact listings. Missing or expired prices do not count toward a complete build total. Verify the exact variant, shipping, taxes and stock before purchasing.</p><h2>Check our work</h2><p>Each guide lists sources so you can review the evidence. Product pages link to their specification sources. See our <a href="/methodology/">data methodology</a> and <a href="/builder/model-coverage/">3D coverage report</a> for current limitations.</p><p><a href="/blog/">Read the Blog</a> · <a href="/blog/feed.xml">Subscribe by RSS</a></p></article>`,{description:'Learn how PC Part Performance sources hardware specifications, labels estimates and 3D models, and publishes researched PC building and AI hardware guides.'}));
 const map={
 '/':['PC Part Performance: Compare Hardware & Build a PC','Compare graphics cards, CPUs, RAM and storage. Plan a compatible PC, explore game FPS estimates, and read practical hardware guides.'],
 '/builder/':['PC Builder & 3D Preview: Parts, Fans and Compatibility','Choose PC components, place case fans, check indexed compatibility and explore supported 3D models. Compare buying options in Canada and the USA.'],
 '/compare/':['Compare PC Parts: GPUs, CPUs, RAM and SSDs','Compare hardware specifications side by side. Choose exact models, inspect product details, and understand the differences before upgrading.'],
 '/hardware/':['PC Hardware Catalog: Specifications & Model Details','Browse graphics cards, processors, motherboards, memory, storage, cases and fans. Find specifications, sources and model-specific buying information.'],
 '/blog/':['PC Hardware Blog: Build Guides, Memory & AI Explained','Read practical PC building guides and sourced explainers on RAM supply, graphics card prices, AI data centers and hardware compatibility.'],
 '/performance/':['Game FPS Calculator & Console Performance Guide','Explore estimated PC game frame rates and sourced console graphics modes. Filter games, select hardware, and check the evidence behind each result.']};
 const productKey=p=>{const name=p.name.toLowerCase(),brand=p.brand.toLowerCase();return brand+' '+(name.startsWith(brand+' ')?name.slice(brand.length+1):name)};
 const canonicalParts=new Map();for(const p of records){const key=productKey(p),old=canonicalParts.get(key),score=x=>(x.physical?1000:0)+Object.keys(x.specs||{}).length;if(!old||score(p)>score(old))canonicalParts.set(key,p)}
 const oldProducts={'x-console-nintendo-switch-2':'switch2','x-console-nintendo-switch-lite':'switchlite'};for(const [old,id]of Object.entries(oldProducts)){const target=domain+'/learn/'+id+'.html';fs.writeFileSync(path.join(root,'learn',old+'.html'),'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Product page moved</title><link rel="canonical" href="'+target+'"><meta http-equiv="refresh" content="0;url='+target+'"></head><body data-legacy-redirect><p><a href="'+target+'">Continue to the product page</a></p></body></html>')}
 const paths=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())walk(f);else if(e.name.endsWith('.html'))paths.push(f)}}walk(root);
 const sitemap=[],report={pages:0,noindex:[],bundles:new Set()};
 for(const file of paths){let h=fs.readFileSync(file,'utf8');if(h.includes('data-legacy-redirect'))continue;const route='/'+path.relative(root,file).replaceAll('\\','/').replace(/index\.html$/,'');const p=records.find(p=>route==='/learn/'+p.id+'.html');
 if(route==='/about/'){h=h.replace('</head>','<link rel="stylesheet" href="/learn.css"></head>').replace('</nav><button class="theme-toggle"','<a href="/shop/">Shop</a></nav><button class="theme-toggle"')}
 if(map[route]){const [title,desc]=map[route];h=h.replace(/<title>[\s\S]*?<\/title>/,`<title>${esc(title)}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${esc(desc)}">`)}
 if(p){const title=`${p.brand} ${p.name.startsWith(p.brand)?p.name.slice(p.brand.length).trim():p.name}: Specs & Compatibility`;const desc=`${p.name}: ${p.summary}. Check ${p.cat==='fan'?'fan dimensions, connectors and airflow direction':'specifications and model details'}, source documentation and buying options.`;h=h.replace(/<title>[\s\S]*?<\/title>/,`<title>${esc(title)} · PC Part Performance</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${esc(desc)}">`)}
 h=h.replace(/<link rel="canonical"[^>]*>/g,'').replace(/<meta name="twitter:(?:title|description)"[^>]*>/g,'');
 h=h.replace(/<meta (?:name="twitter:card"|property="og:(?:title|description|url|site_name|type)") content="[^"]*">/g,'').replace(/<meta name="robots" content="[^"]*">/g,'');
 const title=h.match(/<title>(.*?)<\/title>/)?.[1]||'',desc=h.match(/<meta name="description" content="([^"]*)"/)?.[1]||'',thin=p&&Object.keys(p.specs||{}).length<3&&!p.physical,preferred=p?canonicalParts.get(productKey(p)):null,alternate=preferred&&preferred.id!==p.id,canonical=domain+(alternate?'/learn/'+preferred.id+'.html':route),noindex=route==='/404.html'||(thin&&!alternate);h=h.replace('</head>',`<link rel="canonical" href="${canonical}"></head>`);
 if(noindex)report.noindex.push(route);else if(!alternate)sitemap.push(domain+route);
 const article=articles.find(a=>route==='/blog/'+a.slug+'/'),socialImage=article?.image?.src||'/assets/social-card.png',socialAlt=article?.image?.alt||'PC Part Performance — compare hardware and plan your PC';
 const metadata=`<meta name="robots" content="${noindex?'noindex,follow':'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'}"><meta property="og:type" content="${route.startsWith('/blog/')&&route!=='/blog/'?'article':'website'}"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="PC Part Performance"><meta property="og:image" content="${domain}${socialImage}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="${article?.image?675:630}"><meta property="og:image:alt" content="${esc(socialAlt)}"><meta name="twitter:image" content="${domain}${socialImage}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${desc}"><link rel="alternate" type="application/rss+xml" title="PC Part Performance Blog" href="/blog/feed.xml">`;
 h=h.replace('</head>',metadata+'</head>');h=h.replace('</footer>','<a href="/about/">About &amp; editorial standards</a><a href="/blog/feed.xml">RSS</a></footer>');
 if(p&&!alternate){const data={'@context':'https://schema.org','@type':'Product',name:p.brand+' '+p.name,description:p.summary,category:p.cat,brand:{'@type':'Brand',name:p.brand},url:canonical,additionalProperty:Object.entries(p.specs||{}).map(([name,value])=>({'@type':'PropertyValue',name,value}))};h=h.replace('</head>','<script type="application/ld+json">'+JSON.stringify(data).replace(/</g,'\\u003c')+'</script></head>')}
 if(route==='/')h=h.replace('</head>',`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':domain+'/#website',name:'PC Part Performance',url:domain+'/'},{'@type':'Organization','@id':domain+'/#publisher',name:'PC Part Performance',url:domain+'/about/',logo:domain+'/assets/logo.png'}]})}</script></head>`);
 // Combine the ordered local stylesheets into a content-addressed file. Move font imports into the document head.
 const css=[...h.matchAll(/<link rel="stylesheet" href="(\/[^"?]+\.css)">/g)].map(m=>m[1]);if(css.length){const imports=new Set();let content=css.map(url=>fs.readFileSync(path.join(root,url),'utf8')).join('\n').replace(/\r\n/g,'\n');content=content.replace(/@import url\(([^)]+)\);/g,(_,u)=>{imports.add(u.replace(/^['"]|['"]$/g,''));return''});const hash=crypto.createHash('sha256').update(content).digest('hex').slice(0,12),url='/assets/css/site-'+hash+'.css';fs.mkdirSync(path.join(root,'assets/css'),{recursive:true});fs.writeFileSync(path.join(root,url),content);let first=true;h=h.replace(/<link rel="stylesheet" href="\/[^"?]+\.css">/g,()=>{if(!first)return'';first=false;return[...imports].map(u=>`<link rel="stylesheet" href="${u.replaceAll('&','&amp;')}">`).join('')+`<link rel="stylesheet" href="${url}">`});report.bundles.add(url)}
 if(!h.includes('rel="canonical"'))h=h.replace('</head>',`<link rel="canonical" href="${domain+route}"></head>`);
 fs.writeFileSync(file,h);report.pages++;
 }
 const cssRoot=path.resolve(root,'assets/css');if(cssRoot.startsWith(path.resolve(root)+path.sep)){for(const name of fs.readdirSync(cssRoot)){if(/^site-[a-f0-9]{12}\.css$/.test(name)&&!report.bundles.has('/assets/css/'+name))fs.unlinkSync(path.join(cssRoot,name))}}
 const xml=s=>String(s).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
 fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+[...new Set(sitemap)].sort().map(url=>`<url><loc>${xml(url)}</loc></url>`).join('')+'</urlset>');
 fs.writeFileSync(path.join(root,'blog/feed.xml'),'<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>PC Part Performance Blog</title><link>'+domain+'/blog/</link><description>PC building guides and researched hardware explainers.</description><language>en</language>'+articles.map(a=>`<item><title>${xml(a.title)}</title><link>${domain}/blog/${a.slug}/</link><guid>${domain}/blog/${a.slug}/</guid><description>${xml(a.description)}</description><pubDate>Fri, 18 Sep 2026 12:00:00 GMT</pubDate></item>`).join('')+'</channel></rss>');
 fs.writeFileSync('docs/seo-audit.json',JSON.stringify({...report,bundles:[...report.bundles],notes:['Traffic and field Core Web Vitals not measured; no Search Console connection available.','No meta keywords or ranking guarantees.','Thin product entries remain accessible but are excluded from indexing and sitemap.','Published explainers use Article, not NewsArticle.','Static host did not apply _redirects in the previous deployment; live HTTP status must be verified separately.']},null,2));
 console.log(`SEO: ${report.pages} pages, ${sitemap.length} indexable URLs, ${report.noindex.length} excluded, ${report.bundles.size} stylesheet bundles.`);
};
