const fs=require('fs'),path=require('path');
const {pages,sources}=require('./seo-launch-content.cjs');
const categoryPaths={gpu:'graphics-cards',cpu:'processors',board:'motherboards',ram:'memory',ssd:'solid-state-drives',hdd:'hard-drives',psu:'power-supplies',case:'pc-cases',fan:'case-fans',monitor:'monitors',mouse:'mice',keyboard:'keyboards',microphone:'microphones',headset:'headsets',controller:'controllers',console:'consoles',phone:'phones',handheld:'handhelds'};
module.exports=({root,records,images,groups,shell,write,esc})=>{
 const domain='https://www.pcpartperformance.com',date='2026-10-03',byId=new Map(records.map(p=>[p.id,p]));
 const update=(route,fn)=>{const file=path.join(root,route,'index.html');fs.writeFileSync(file,fn(fs.readFileSync(file,'utf8')))};
 const photo=p=>images[p.id]?`<img src="${esc(images[p.id].src)}" alt="${esc(images[p.id].picturedModel)}" width="800" height="500" loading="lazy" decoding="async">`:'';
 const breadcrumbs=(title,parent='/blog/',parentName='Blog')=>({ '@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:domain+'/'},{'@type':'ListItem',position:2,name:parentName,item:domain+parent},{'@type':'ListItem',position:3,name:title,item:domain+'/'+title.route+'/'}]});
 const schema=data=>`<script type="application/ld+json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script>`;
 const pagination=(base,current,count)=>`<nav class="catalog-pagination" aria-label="Catalog pages">${Array.from({length:count},(_,i)=>`<a href="/${base}/${i?`page/${i+1}/`:''}"${i+1===current?' aria-current="page"':''}>${i+1}</a>`).join('')}</nav>`;
 const row=p=>`<tr><td><a class="catalog-product" href="/learn/${esc(p.id)}.html">${photo(p)}<span class="catalog-product-copy"><strong>${esc(p.name)}</strong><span>${esc(p.brand)} · ${esc(p.architecture)}</span></span></a></td><td>${esc(groups.find(g=>g[0]===p.cat)?.[1]||p.cat)}</td><td>${p.year||'Unavailable'}</td><td>${esc(p.summary)}</td><td><a href="/compare/?parts=${encodeURIComponent(p.id)}">Compare</a></td></tr>`;
 const sorted=rows=>rows.slice().sort((a,b)=>(b.year||0)-(a.year||0));
 const directory=`<nav class="catalog-directory" aria-label="Hardware categories">${groups.map(([cat,label])=>`<a href="/hardware/${categoryPaths[cat]}/">${esc(label)}</a>`).join('')}</nav>`;
 let paginationPages=0;
 for(const [cat,label]of [['','Hardware catalog'],...groups]){
  const base=cat?'hardware/'+categoryPaths[cat]:'hardware',rows=sorted(records.filter(p=>!cat||p.cat===cat)),count=Math.ceil(rows.length/24);
  if(!rows.length)continue;
    if(!['','gpu','cpu','ram','ssd'].includes(cat))write(base,shell(label,'hardware',`<header class="page-heading"><div><h1>${esc(label)}</h1><p>Browse indexed specifications and exact model details.</p></div></header><div class="catalog-tools"><label class="search-field"><input id="catalog-search" type="search" placeholder="Search model or brand" aria-label="Search hardware"></label><select id="catalog-category" aria-label="Hardware category"></select><select id="catalog-era" aria-label="Release period"><option value="all">All generations</option><option value="modern">2020–present</option><option value="legacy">Before 2020</option></select><select id="catalog-sort" aria-label="Sort hardware"><option value="new">Newest first</option><option value="old">Oldest first</option><option value="name">Name A–Z</option></select></div><div class="catalog-meta"><span id="catalog-summary"></span><a id="selected-link" href="/compare/">Compare selected</a></div><div class="table-scroll"><table class="hardware-table"><thead><tr><th>Hardware</th><th>Category</th><th>Released</th><th>Specification</th><th>Compare</th></tr></thead><tbody id="hardware-rows"></tbody></table></div><div id="catalog-empty" hidden></div><button id="catalog-more" class="button secondary load-more">Show more</button>`,{category:cat,description:`Browse ${label.toLowerCase()} by exact model. Check indexed specifications, source links and product details before planning a PC upgrade.`}));
  update(base,h=>h.replace('<tbody id="hardware-rows"></tbody>',`<tbody id="hardware-rows">${rows.slice(0,24).map(row).join('')}</tbody>`).replace('<span id="catalog-summary" aria-live="polite"></span>',`<span id="catalog-summary" aria-live="polite">${Math.min(24,rows.length)} of ${rows.length} parts</span>`).replace('<span id="catalog-summary"></span>',`<span id="catalog-summary">${Math.min(24,rows.length)} of ${rows.length} parts</span>`).replace('No matching hardware. Try a different model or category.','').replace('<div class="catalog-tools">',directory+'<div class="catalog-tools">').replace('</main>',pagination(base,1,count)+`<noscript><p>Search and selection use JavaScript. The numbered pages and product details remain available.</p></noscript></main>`));
  for(let i=2;i<=count;i++){
   const route=base+'/page/'+i;
   write(route,shell(`${label}: page ${i}`,'catalog-page',`<header class="page-heading"><div><h1>${esc(label)}: page ${i}</h1><p>${(i-1)*24+1}–${Math.min(i*24,rows.length)} of ${rows.length} indexed parts</p></div><a class="button secondary" href="/${base}/">Search catalog</a></header>${directory}<div class="table-scroll"><table class="hardware-table"><thead><tr><th>Hardware</th><th>Category</th><th>Released</th><th>Specification</th><th>Compare</th></tr></thead><tbody>${rows.slice((i-1)*24,i*24).map(row).join('')}</tbody></table></div>${pagination(base,i,count)}`,{description:`Browse page ${i} of the ${label.toLowerCase()}. Open model specifications and source documentation.`}));paginationPages++;
  }
 }
 const tools={
  ram:`<form class="research-calculator" data-calculator="ram"><h2>Compare two memory profiles</h2><div class="calculator-inputs">${['A','B'].map((letter,i)=>`<fieldset><legend>Profile ${letter}</legend><label>Transfer rate (MT/s)<input name="rate${letter}" type="number" min="1" max="100000" step="1" value="6000" required></label><label>CAS latency (cycles)<input name="cl${letter}" type="number" min="1" max="1000" step="1" value="${i?36:30}" required></label></fieldset>`).join('')}</div><button class="button primary" type="submit">Calculate latency</button><output aria-live="polite">Profile A: 10.00 ns. Profile B: 12.00 ns. Calculated first-word CAS interval.</output><noscript><p>Use CL × 2,000 ÷ MT/s manually. Interactive inputs need JavaScript.</p></noscript></form>`,
  storage:`<form class="research-calculator" data-calculator="storage"><h2>Plan your drive capacity</h2><div class="calculator-inputs"><label>Advertised drive capacity (TB)<input name="tb" type="number" min="0.001" max="1000" step="any" value="1" required></label><label>Operating system and apps (GiB)<input name="apps" type="number" min="0" max="1000000" step="any" value="100" required></label><label>Games (GiB)<input name="games" type="number" min="0" max="1000000" step="any" value="400" required></label><label>Personal and project files (GiB)<input name="files" type="number" min="0" max="1000000" step="any" value="100" required></label><label>Free-space allowance (%)<input name="reserve" type="number" min="0" max="99" step="any" value="10" required></label></div><button class="button primary" type="submit">Calculate storage budget</button><output aria-live="polite">1 TB = 931.32 GiB before formatting. With a 10% allowance and 600 GiB planned, the balance is 238.19 GiB.</output><noscript><p>Use TB × 10¹² ÷ 2³⁰ × (1 − allowance ÷ 100), then subtract your file budget. Interactive inputs need JavaScript.</p></noscript></form>`
 };
 for(const a of pages){
  const linkLabel=url=>pages.find(p=>'/'+p.route+'/'===url)?.title||groups.find(([cat])=>url==='/hardware/'+categoryPaths[cat]+'/')?.[1]||({'/builder/':'Plan your PC build','/builder/model-coverage/':'Check 3D model coverage','/methodology/#fps':'How FPS estimates work','/learn/990pro.html':'Samsung 990 PRO 1 TB specifications','/blog/will-a-graphics-card-fit-my-case/':'Will this graphics card fit your case?','/blog/how-to-choose-gaming-ram/':'Choose memory for your games'})[url]||url.split('/').filter(Boolean).at(-1).replaceAll('-',' ');
  const url=domain+'/'+a.route+'/',related=a.links.map(url=>`<a href="${url}">${esc(linkLabel(url))}</a>`).join('');
  const pair=a.ids?.map(id=>{const p=byId.get(id),slots=Array(8).fill('');slots[p.cat==='gpu'?2:0]=id;return `<article>${photo(p)}<h2><a href="/learn/${id}.html">${esc(p.name)}</a></h2><p><a href="${esc(images[id]?.sourceUrl||p.source)}" target="_blank" rel="noopener noreferrer">${esc(images[id]?.picturedModel||p.brand)}</a></p><a class="button secondary" href="/builder/?build=${encodeURIComponent(slots.join(','))}">Start a build with this ${p.cat==='gpu'?'GPU':'CPU'}</a></article>`}).join('');
  const table=a.rows?`<div class="article-table-wrap" tabindex="0" role="region" aria-label="Comparison specifications"><table class="article-table"><caption>Manufacturer specifications, checked October 3, 2026</caption><thead><tr><th scope="col">Specification</th>${a.ids.map(id=>`<th scope="col">${esc(byId.get(id).name)}</th>`).join('')}</tr></thead><tbody>${a.rows.map(row=>`<tr>${row.map((cell,i)=>`<${i?'td':'th scope="row"'}>${esc(cell)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`:'';
  const dates=a.type==='pillar'?'<span>Revised October 3, 2026 · Original publication date not recorded</span>':'<time datetime="2026-10-03">October 3, 2026</time>';
  const articleSchema={'@type':a.type==='tool'?'WebPage':'Article',...(a.type==='tool'?{name:a.title}:{headline:a.title,author:{'@type':'Organization',name:'PC Part Performance',url:domain+'/about/'},publisher:{'@type':'Organization',name:'PC Part Performance',url:domain+'/about/'},...(a.type==='pillar'?{}:{datePublished:date}),dateModified:date}),description:a.description,url,mainEntityOfPage:url};
  const bc=breadcrumbs({route:a.route},a.type==='comparison'?'/compare/':a.type==='tool'?'/tools/':'/blog/',a.type==='comparison'?'Comparisons':a.type==='tool'?'Tools':'Blog');bc.itemListElement[2].name=a.title;
  const citationMap={
   'blog/how-to-choose-a-graphics-card':{1:['test5070'],2:['n5070','n5060']},
   'blog/how-to-choose-a-processor':{1:['cpuGuide','clocks'],2:['boardSpecs']},
   'blog/understanding-pc-memory':{0:['cpu9800'],2:['ram'],3:['boardSpecs']},
   'blog/choosing-an-ssd':{1:['ssd'],2:['boardSpecs'],4:['capacity']},
   'compare/rtx-5070-vs-rtx-5060-ti-16gb':{0:['n5070','n5060'],1:['test5070']},
   'compare/rtx-5070-vs-rx-9070':{0:['n5070','rx9070'],1:['test9070']},
   'compare/ryzen-7-9800x3d-vs-7800x3d':{0:['cpu9800','cpu7800']},
   'blog/am5-upgrade-checklist':{3:['boardSpecs']},
   'tools/ram-latency-calculator':{0:['ram']},'tools/storage-capacity-planner':{0:['capacity']}
  };
  const html=`${schema({'@context':'https://schema.org','@graph':[articleSchema,bc]})}<nav class="article-breadcrumb" aria-label="Breadcrumb"><a href="${a.type==='comparison'?'/compare/':a.type==='tool'?'/tools/':'/blog/'}">${a.type==='comparison'?'Comparisons':a.type==='tool'?'Tools':'Blog'}</a><span aria-hidden="true">/</span><span>${esc(a.category)}</span></nav><header class="article-header"><h1>${esc(a.title)}</h1><p>${esc(a.description)}</p><div class="article-byline">By <a href="/about/">PC Part Performance</a> · ${dates}</div></header>${pair?`<div class="research-pair">${pair}</div>`:''}<div class="article-layout"><nav class="article-toc" aria-label="On this page"><strong>On this page</strong>${a.sections.map(([title],i)=>`<a href="#section-${i}">${esc(title)}</a>`).join('')}<a href="#sources">Sources</a></nav><article class="article-copy"><div class="article-answer"><strong>The short answer</strong><p>${esc(a.answer)}</p></div>${a.tool?tools[a.tool]:''}${table}${a.sections.map(([title,...paragraphs],i)=>`<section id="section-${i}"><h2>${esc(title)}</h2>${paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}${(citationMap[a.route]?.[i]||[]).map(id=>`<p class="inline-source">Source: <a href="${sources[id][1]}" target="_blank" rel="noopener noreferrer">${esc(sources[id][0])}</a></p>`).join('')}</section>`).join('')}<section id="sources"><h2>Sources</h2><p>Research checked October 3, 2026. Specifications are published data; calculations are illustrative; no hands-on benchmark results or current retailer prices are claimed.</p><ul class="article-sources">${a.sources.map(id=>`<li><a href="${esc(sources[id][1])}" target="_blank" rel="noopener noreferrer">${esc(sources[id][0])}</a></li>`).join('')}</ul></section>${a.type==='pillar'?'<p class="revision-note">Revision: expanded the decision checklist, platform requirements, source notes and links on October 3, 2026.</p>':''}<nav class="related-guides" aria-label="Related resources"><h2>Use these checks</h2>${related}</nav><p><a href="/editorial-policy/#corrections">Report an error</a> · <a href="/methodology/">Data methodology</a></p></article></div>`;
  write(a.route,shell(a.title,'guide',html,{description:a.description,active:a.type==='comparison'?'compare':a.type==='tool'?'tools':'learn'}));
 }
 const cards=list=>list.map(a=>`<article><h3><a href="/${a.route}/">${esc(a.title)}</a></h3><p>${esc(a.description)}</p></article>`).join('');
 write('tools',shell('PC planning calculators and data tools','guide',`<header class="article-header"><h1>PC planning tools</h1><p>Transparent calculations for memory and storage. Every tool explains its inputs and limits.</p></header><div class="feature-list">${cards(pages.filter(a=>a.type==='tool'))}</div><p class="data-note">More checks: <a href="/builder/">PC builder</a> · <a href="/builder/model-coverage/">3D coverage report</a> · <a href="/methodology/">Methodology</a></p>`,{description:'Calculate RAM CAS timing and plan SSD capacity with explicit formulas. Explore PC compatibility checks, hardware data and 3D model coverage.'}));
 update('compare',h=>h.replace('</main>',`<noscript><p>Interactive hardware selection needs JavaScript. The researched comparisons below include specifications and decision guidance without it.</p></noscript><section class="learn-features"><h2>Researched hardware comparisons</h2><div class="feature-list">${cards(pages.filter(a=>a.type==='comparison'))}</div></section></main>`));
 update('blog',h=>h.replace('</main>',`<section class="learn-features"><h2>Upgrade checklists and calculators</h2><div class="feature-list">${cards(pages.filter(a=>['guide','tool'].includes(a.type)))}</div></section></main>`));
 update('',h=>h.replaceAll('/compare/?parts=rtx5070,rtx5060ti16','/compare/rtx-5070-vs-rtx-5060-ti-16gb/').replace('</main>','<section class="learn-features"><h2>Plan the details</h2><div class="feature-list">'+cards(pages.filter(a=>a.type==='tool'))+'</div></section></main>'));
 write('editorial-policy',shell('Editorial standards, disclosures and corrections','guide',`<header class="article-header"><h1>Editorial standards and corrections</h1><p>How PC Part Performance publishes and maintains its hardware resources.</p></header><article class="article-copy" style="max-width:760px;margin:32px auto"><h2>Authorship and testing</h2><p>Site-produced guides use the PC Part Performance organizational byline. We do not claim laboratory testing or an expert reviewer where none exists. Manufacturer specifications, independent testing and our own calculations are identified separately.</p><h2>Updates and source changes</h2><p>We revise a page’s modification date when its evidence or guidance changes materially. A missing original publication date stays missing. Price snapshots expire rather than becoming permanent recommendations. Review launch-sensitive specifications at each release and evergreen guides every quarter.</p><h2>Buying links and disclosures</h2><p>Store searches can include another variant, used items or unavailable listings. Confirm exact model, stock, tax and shipping. We do not call a search link a verified offer. If an affiliate relationship is introduced, disclose it next to the buying section and mark paid links appropriately; this page does not claim that such a relationship currently exists.</p><h2>Images and 3D previews</h2><p>Alt text identifies the pictured item. Reference chip entries can show a named partner card. Model coverage and creator credits document the source and verification limits. A loadable 3D model is not a clearance guarantee.</p><h2 id="corrections">Report an error</h2><p>Use the repository issue form to provide the page URL, exact model or product ID, incorrect field, suggested correction and a supporting manufacturer or original-testing link. Do not include personal information.</p><a class="button secondary" href="https://github.com/LukasJT/pcpartperformance/issues/new?template=data-correction.yml" target="_blank" rel="noopener noreferrer">Submit a data correction</a><p>Issue submission requires a GitHub account. We do not promise a response time. An editor should verify the source, update all affected pages, record a material revision and close the issue with the correction.</p><h2>Retiring a page</h2><p>Keep useful historical specifications with their dates. Redirect only when a genuine replacement exists. Remove misleading or unsupported advice; do not change dates to create the appearance of current reporting.</p><p><a href="/about/">About the site</a> · <a href="/methodology/">Calculation and data methods</a></p></article>`,{description:'Read PC Part Performance’s sourcing, authorship, testing, price, image, correction and update policies. Report hardware data errors with supporting evidence.'}));
 update('methodology',h=>h.replace('Each game has a calibrated 1080p workload baseline.','Each game has an assumed 1080p workload baseline. Calibration against a documented independent test set has not been established.').replace('The displayed low and high values add a conservative variance band for drivers, patches, thermals, memory and scene complexity.','The displayed bands and estimated 1% lows are fixed model multipliers. They have not been validated as statistical ranges or measured frame-time percentiles.').replace('Data and photo sources','Hardware data, FPS estimates and compatibility methodology'));
 update('builder/model-coverage',h=>h.replace('Updated September 23, 2026.','Generated from the current local model manifest. Geometry and mount-point verification dates are not recorded for all entries.'));
 fs.writeFileSync(path.join(root,'comparison-routes.json'),JSON.stringify(Object.fromEntries(pages.filter(p=>p.ids).map(p=>[p.ids.slice().sort().join(','),'/'+p.route+'/']))));
 fs.writeFileSync('docs/seo-launch-manifest.json',JSON.stringify({researchDate:date,pages:pages.map(({sections,published,...p})=>({...p,publicationDate:p.type==='pillar'?null:date,modifiedDate:date,sectionTitles:sections.map(s=>s[0]),wordCount:sections.flat().join(' ').split(/\s+/).length})),paginationPages,categories:groups.length},null,2));
};
module.exports.categoryPaths=categoryPaths;
