const fs=require('fs'),path=require('path');
module.exports=({root,records,images,groups,shell,esc,write})=>{
const domain='https://www.pcpartperformance.com';
const flag=`<div class="country-switch" role="group" aria-label="Shopping country"><button type="button" data-region="CA" aria-pressed="true" aria-label="Shop in Canada, Canadian dollars"><img src="/assets/flag-ca.svg" alt="" width="21" height="14"><span>CA</span></button><button type="button" data-region="US" aria-pressed="false" aria-label="Shop in the United States, US dollars"><img src="/assets/flag-us.svg" alt="" width="21" height="14"><span>US</span></button></div>`;
const json=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const catalog=records.map(p=>({id:p.id,name:p.name,brand:p.brand,cat:p.cat,year:p.year,summary:p.summary,image:images[p.id]?.src||'/assets/favicon.svg',alt:images[p.id]?.picturedModel||p.name}));
fs.writeFileSync(path.join(root,'shopping-catalog.json'),JSON.stringify(catalog));
write('shop',shell('Shop PC parts in Canada and the USA','shop',`<div class="page-heading"><div><h1>Shop hardware</h1><p>Find your parts. Compare buying options.</p></div><a class="button secondary" href="/builder/">Plan a build</a></div><div class="shop-tools"><label class="shop-search-field"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input type="search" id="shop-search" placeholder="Search products or brands" aria-label="Search products or brands"></label></div><details class="shop-filters"><summary><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="2" fill="var(--surface)"/><circle cx="15" cy="17" r="2" fill="var(--surface)"/></svg><span>Filters</span><span id="filter-count"></span><span class="filter-summary-hint">Category, brand &amp; series</span><svg class="filter-toggle" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m5 7 5 5 5-5"/></svg></summary><div class="filter-panel"><div class="filter-panel-top"><strong>Narrow your search</strong><button type="button" class="text-button" id="filter-clear" hidden>Clear filters</button></div><div class="filter-columns"><fieldset><legend>Part type</legend><div id="filter-category" class="filter-options"></div></fieldset><fieldset><legend>Brand</legend><div id="filter-brand" class="filter-options"></div></fieldset><fieldset id="series-fieldset" hidden><legend>Graphics card series</legend><div id="filter-series" class="filter-options"></div></fieldset></div><label class="filter-choice price-filter"><input type="checkbox" id="shop-priced"><span>Only show products with prices</span></label></div></details><div id="filter-chips" class="filter-chips" hidden></div><div class="shop-meta"><span id="shop-count" role="status">Loading products…</span><span>Featured parts first</span></div><div class="shop-grid" id="shop-results"></div><button class="button secondary load-more" id="shop-more" hidden>Show more products</button><noscript><p><a href="/hardware/">Browse the hardware catalog</a> for product details and retailer links.</p></noscript>`,{description:'Shop PC parts in Canada and the USA. Filter graphics cards, CPUs, memory and storage by brand and series, and explore retailer prices in CAD and USD.'}));
const sitemap=[];
function walk(dir){for(const f of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,f.name);if(f.isDirectory())walk(full);else if(f.name.endsWith('.html')){
let html=fs.readFileSync(full,'utf8'),rel=path.relative(root,full).replaceAll('\\','/'),route='/'+rel.replace(/index\.html$/,'');
const p=rel.startsWith('learn/')?records.find(p=>rel==='learn/'+p.id+'.html'):null;
html=html.replace('</head>','<link rel="stylesheet" href="/shopping.css">'+(route==='/shop/'?'<script src="/shop-filters.js" defer></script>':'')+'<script src="/shopping.js" defer></script></head>');
html=html.replace('<button class="theme-toggle"',flag+'<button class="theme-toggle"');
html=html.replace('</nav><div class="country-switch"','<a href="/shop/"'+(route==='/shop/'?' aria-current="page"':'')+'>Shop</a></nav><div class="country-switch"');

if(p){const q=encodeURIComponent(p.brand+' '+p.name),links=[['Newegg Canada','https://www.newegg.ca/p/pl?d='],['Newegg USA','https://www.newegg.com/p/pl?d=']].map(([label,url])=>`<a href="${url+q}" target="_blank" rel="noopener noreferrer">Search ${label} ↗</a>`).join(' ');
const buy=`<section id="buy" class="buy-section" aria-labelledby="buy-title"><div class="buy-heading"><div><h2 id="buy-title">Where to buy</h2><p>Find ${esc(p.name)} at a retailer.</p></div><span data-shopping-country>Canada · CAD</span></div><div data-product-buy>${links}</div><p class="buy-note">Checked prices expire after 24 hours. Tax and shipping are extra. Store search results may include other variants or used items; confirm the model before buying. <a href="/methodology/#shopping">About prices</a></p></section><script type="application/json" id="shopping-product">${json({id:p.id,name:p.name,brand:p.brand,cat:p.cat,summary:p.summary})}</script>`;
html=html.replace('<div class="record-detail">',buy+'<div class="record-detail">');
html=html.replace(/<figcaption>[\s\S]*?<\/figcaption>/g,'');
html=html.replace(/<p>(?:Official product photo|Product photo|Product family photo|Reference photo): /g,'<p>Pictured: ');
html=html.replace(/ — reference photo, not this exact model| — product family photo/g,'');
const schema={'@context':'https://schema.org','@type':'Product',name:p.name,brand:{'@type':'Brand',name:p.brand},description:p.summary,url:domain+route};if(images[p.id]?.kind==='exact')schema.image=domain+images[p.id].src;
html=html.replace('</head>',`<script type="application/ld+json">${json(schema)}</script></head>`);
}
if(route==='/builder/')html=html.replace('<div class="builder-rail">','<div class="builder-rail"><section class="shopping-summary" id="build-shopping-summary" aria-label="Build shopping subtotal" aria-live="polite"></section>');
if(route==='/methodology/')html=html.replace('<div class="method-grid">','<div class="method-grid"><details id="shopping" open><summary>Shopping and prices</summary><p>Choose Canada for CAD or the United States for USD. Buying links are available for every catalog entry. Search links do not guarantee availability or a matching variant.</p><p>Checked prices are time-stamped snapshots of exact retailer listings. They expire after 24 hours and are not automatically refreshed continuously. Lowest checked price means the lowest among the displayed offers, not every retailer. Coverage is limited while more product listings and retailer feeds are connected.</p><p>Build subtotals include only parts with a valid checked price, including repeated items. Missing prices are excluded and counted separately. Taxes, shipping, coupons, mail-in rebates and membership discounts are not included. Confirm final pricing and stock at checkout.</p></details>');
const title=html.match(/<title>(.*?)<\/title>/)?.[1]||'PC Part Performance',description=html.match(/<meta name="description" content="([^"]*)"/)?.[1]||'';
html=html.replace('</head>',`<link rel="canonical" href="${domain+route}"><meta property="og:type" content="website"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${domain+route}"><meta property="og:site_name" content="PC Part Performance"><meta name="twitter:card" content="summary">${rel==='404.html'?'<meta name="robots" content="noindex">':''}</head>`);
fs.writeFileSync(full,html);if(rel!=='404.html')sitemap.push(domain+route);
}}}walk(root);
fs.writeFileSync(path.join(root,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: '+domain+'/sitemap.xml\n');
fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+sitemap.sort().map(url=>'<url><loc>'+esc(url)+'</loc></url>').join('')+'</urlset>');
};
