// STEP tessellation through occt-import-js 0.0.23. Conversion runs offline;
// the website receives only the resulting GLB, never the CAD runtime.
const fs=require('fs'),path=require('path');
const [runtime,source,output]=process.argv.slice(2);
if(!output)throw Error('Usage: node step-to-glb.cjs runtime-directory source.step output.glb');
(async()=>{
 const occt=await require(path.resolve(runtime))();
 const result=occt.ReadStepFile(fs.readFileSync(source),{linearUnit:'meter',linearDeflectionType:'absolute_value',linearDeflection:0.00015,angularDeflection:0.2});
 if(!result.success||!result.meshes.length)throw Error('STEP import failed');
 const doc={asset:{version:'2.0',generator:'PC Part Performance STEP conversion / occt-import-js 0.0.23'},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],materials:[],accessors:[],bufferViews:[],buffers:[{byteLength:0}]};const chunks=[];let offset=0;
 function accessor(values,components,index=false){const array=index?new Uint32Array(values):new Float32Array(values),buf=Buffer.from(array.buffer);const view=doc.bufferViews.length;doc.bufferViews.push({buffer:0,byteOffset:offset,byteLength:buf.length,target:index?34963:34962});chunks.push(buf);offset+=buf.length;const a={bufferView:view,componentType:index?5125:5126,count:values.length/components,type:components===3?'VEC3':'SCALAR'};if(!index){a.min=Array(components).fill(Infinity);a.max=Array(components).fill(-Infinity);for(let i=0;i<values.length;i++){a.min[i%components]=Math.min(a.min[i%components],values[i]);a.max[i%components]=Math.max(a.max[i%components],values[i]);}}doc.accessors.push(a);return doc.accessors.length-1;}
 const materialMap=new Map();function material(color){color=color||[.6,.55,.45];const key=color.join(',');if(!materialMap.has(key)){materialMap.set(key,doc.materials.length);doc.materials.push({pbrMetallicRoughness:{baseColorFactor:[...color,1],metallicFactor:0,roughnessFactor:.65},doubleSided:true});}return materialMap.get(key);}
 for(const mesh of result.meshes){const attributes={POSITION:accessor(mesh.attributes.position.array,3)};if(mesh.attributes.normal)attributes.NORMAL=accessor(mesh.attributes.normal.array,3);const primitives=[];const faces=mesh.brep_faces||[];if(faces.length){const groups=new Map();for(const face of faces){const mat=material(face.color||mesh.color);if(!groups.has(mat))groups.set(mat,[]);const indices=groups.get(mat);for(let i=face.first*3;i<(face.last+1)*3;i++)indices.push(mesh.index.array[i]);}for(const [mat,indices]of groups)if(indices.length)primitives.push({attributes,indices:accessor(indices,1,true),material:mat});}else primitives.push({attributes,indices:accessor(mesh.index.array,1,true),material:material(mesh.color)});doc.meshes.push({name:mesh.name,primitives});doc.nodes.push({name:mesh.name,mesh:doc.meshes.length-1});doc.scenes[0].nodes.push(doc.nodes.length-1);}
 doc.buffers[0].byteLength=offset;let json=Buffer.from(JSON.stringify(doc));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);const bin=Buffer.concat(chunks);const header=Buffer.alloc(20);header.writeUInt32LE(0x46546c67,0);header.writeUInt32LE(2,4);header.writeUInt32LE(28+json.length+bin.length,8);header.writeUInt32LE(json.length,12);header.writeUInt32LE(0x4e4f534a,16);const bh=Buffer.alloc(8);bh.writeUInt32LE(bin.length,0);bh.writeUInt32LE(0x004e4942,4);fs.writeFileSync(output,Buffer.concat([header,json,bh,bin]));console.log(output,doc.meshes.length,'meshes',bin.length,'geometry bytes');
})();
